exports.ClassIds = "63bba1e60e730c573767a1e3";

exports.studentsListQuery = [
  {
    studentFirstName: "Rydham",
    studentMiddleName: "Rajesh",
    studentLastName: "Pariyar",
    studentPhoneNumber: 8265074512,
    studentDOB: "2019-10-26",
    studentGender: "Female",
  },
  {
    studentFirstName: "Siya",
    studentMiddleName: "Sushant",
    studentLastName: "kale",
    studentPhoneNumber: 9960246613,
    studentDOB: "2019-03-18",
    studentGender: "Female",
  },
  {
    studentFirstName: "Anushka",
    studentMiddleName: "Krushna",
    studentLastName: "Diyal",
    studentPhoneNumber: 8265074592,
    studentDOB: "2019-12-15",
    studentGender: "Female",
  },
  {
    studentFirstName: "Trisha",
    studentMiddleName: "Ganesh",
    studentLastName: "gavali",
    studentPhoneNumber: 7875031696,
    studentDOB: "2018-05-20",
    studentGender: "Female",
  },
  {
    studentFirstName: "Devansh",
    studentMiddleName: "Bhimraj",
    studentLastName: "Kadam",
    studentPhoneNumber: 9730384489,
    studentDOB: "2018-02-13",
    studentGender: "Male",
  },
  {
    studentFirstName: "Kartiki",
    studentMiddleName: "Satish",
    studentLastName: "Kame",
    studentPhoneNumber: 9890768641,
    studentDOB: "2019-01-30",
    studentGender: "Female",
  },
  {
    studentFirstName: "Khushi",
    studentMiddleName: "Ratnabahad",
    studentLastName: "Mahajara",
    studentPhoneNumber: 8637728467,
    studentDOB: "2019-10-22",
    studentGender: "Female",
  },
  {
    studentFirstName: "Ruhi",
    studentMiddleName: "Manoj",
    studentLastName: "Shardul",
    studentPhoneNumber: 8850685258,
    studentDOB: "2019-06-27",
    studentGender: "Male",
  },
  {
    studentFirstName: "Yuvraj",
    studentMiddleName: "Bhagwan",
    studentLastName: "Karpe",
    studentPhoneNumber: 7588986630,
    studentDOB: "2018-02-01",
    studentGender: "Male",
  },
  {
    studentFirstName: "Glori",
    studentMiddleName: "Hanmantha",
    studentLastName: "Chiluka",
    studentPhoneNumber: 9603586497,
    studentDOB: "2019-07-03",
    studentGender: "Female",
  },
];
