const location = [
    { id: '1', district: '', state: 'Andhra Pradesh', pincode: '', landmark: ''},
    { id: '2', district: '', state: 'Arunachal Pradesh', pincode: '', landmark: ''},
    { id: '3', district: '', state: 'Assam', pincode: '', landmark: ''},
    { id: '4', district: '', state: 'Bihar', pincode: '', landmark: ''},
    { id: '5', district: '', state: 'Chhattishgarh', pincode: '', landmark: ''},
    { id: '6', district: '', state: 'Goa', pincode: '', landmark: ''},
    { id: '7', district: '', state: 'Gujarat', pincode: '', landmark: ''},
    { id: '8', district: '', state: 'Haryana', pincode: '', landmark: ''},
    { id: '9', district: '', state: 'Himanchal Pradesh', pincode: '', landmark: ''},
    { id: '10', district: '', state: 'Jammu & Kashmir', pincode: '', landmark: ''},
    { id: '11', district: '', state: 'Jharkhand', pincode: '', landmark: ''},
    { id: '12', district: '', state: 'Karnataka', pincode: '', landmark: ''},
    { id: '13', district: '', state: 'Kerala', pincode: '', landmark: ''},
    { id: '14', district: '', state: 'Madhya Pradesh', pincode: '', landmark: ''},
    { id: '15', district: '', state: 'Maharashtra', pincode: '', landmark: ''},
    { id: '16', district: '', state: 'Manipur', pincode: '', landmark: ''},
    { id: '17', district: '', state: 'Meghalaya', pincode: '', landmark: ''},
    { id: '18', district: '', state: 'Mizoram', pincode: '', landmark: ''},
    { id: '19', district: '', state: 'Nagaland', pincode: '', landmark: ''},
    { id: '20', district: '', state: 'Odisha', pincode: '', landmark: ''},
    { id: '21', district: '', state: 'Punjab', pincode: '', landmark: ''},
    { id: '22', district: '', state: 'Rajasthan', pincode: '', landmark: ''},
    { id: '23', district: '', state: 'Sikkim', pincode: '', landmark: ''},
    { id: '24', district: '', state: 'Tamil Nadu', pincode: '', landmark: ''},
    { id: '25', district: '', state: 'Telangana', pincode: '', landmark: ''},
    { id: '26', district: '', state: 'Tripura', pincode: '', landmark: ''},
    { id: '27', district: '', state: 'Uttar Pradesh', pincode: '', landmark: ''},
    { id: '28', district: '', state: 'Uttarakhand', pincode: '', landmark: ''},
    { id: '29', district: '', state: 'West Bengal', pincode: '', landmark: ''},
]