const location = [
    { id: '1', district: 'Anantapur', state: 'Andhra Pradesh', pincode: '515001'},
    { id: '1AP', district: 'Chittoor', state: 'Andhra Pradesh', pincode: '517001'},
    { id: '2AP', district: 'East Godavari', state: 'Andhra Pradesh', pincode: '533001'},
    { id: '3AP', district: 'Guntur', state: 'Andhra Pradesh', pincode: '522002'},
    { id: '4AP', district: 'Krishna', state: 'Andhra Pradesh', pincode: '521201'},
    { id: '5AP', district: 'Kadapa (Cuddapah)', state: 'Andhra Pradesh', pincode: '516001'},
    { id: '6AP', district: 'Kurnool', state: 'Andhra Pradesh', pincode: '518001'},
    { id: '7AP', district: 'Prakasam', state: 'Andhra Pradesh', pincode: '523001'},
    { id: '8AP', district: 'Srikakulam', state: 'Andhra Pradesh', pincode: '532001'},
    { id: '9AP', district: 'Sri Potti Sriramulu Nellore', state: 'Andhra Pradesh', pincode: '524322'},
    { id: '10AP', district: 'Vijaywada', state: 'Andhra Pradesh', pincode: '520001'},
    { id: '11AP', district: 'Visakhapatnam', state: 'Andhra Pradesh', pincode: '530001'},
    { id: '12AP', district: 'Vizianagaram', state: 'Andhra Pradesh', pincode: '535002'},

    { id: '2', district: 'Anjaw', state: 'Arunachal Pradesh', pincode: '791110'},
    { id: '2AAP', district: 'Changlang', state: 'Arunachal Pradesh', pincode: '792102'},
    { id: '3AAP', district: 'Dibang Valley', state: 'Arunachal Pradesh', pincode: '792101'},
    { id: '4AAP', district: 'East Kameng', state: 'Arunachal Pradesh', pincode: '790102'},
    { id: '5AAP', district: 'East Siang', state: 'Arunachal Pradesh', pincode: '791102'},
    { id: '6AAP', district: 'Itanagar', state: 'Arunachal Pradesh', pincode: '791111'},
    { id: '7AAP', district: 'Kra Daadi', state: 'Arunachal Pradesh', pincode: '791001'},
    { id: '8AAP', district: 'Kurung Kumey', state: 'Arunachal Pradesh', pincode: '791118'},
    { id: '9AAP', district: 'Lohit', state: 'Arunachal Pradesh', pincode: '792001'},
    { id: '10AAP', district: 'Longding', state: 'Arunachal Pradesh', pincode: '792131'},
    { id: '11AAP', district: 'Lower Dibang Valley', state: 'Arunachal Pradesh', pincode: '792110'},
    { id: '12AAP', district: 'Lower Subansiri', state: 'Arunachal Pradesh', pincode: '791120'},
    { id: '13AAP', district: 'Namsai', state: 'Arunachal Pradesh', pincode: '792103'},
    { id: '14AAP', district: 'Papumpare', state: 'Arunachal Pradesh', pincode: '791112'},
    { id: '15AAP', district: 'Shiyomi', state: 'Arunachal Pradesh', pincode: '791003'},
    { id: '16AAP', district: 'Tawang', state: 'Arunachal Pradesh', pincode: '790104'},
    { id: '17AAP', district: 'Tirap', state: 'Arunachal Pradesh', pincode: '786182'},
    { id: '18AAP', district: 'Upper Siang', state: 'Arunachal Pradesh', pincode: '791002'},
    { id: '19AAP', district: 'Upper Subansiri', state: 'Arunachal Pradesh', pincode: '791122'},
    { id: '20AAP', district: 'West Kameng', state: 'Arunachal Pradesh', pincode: '790101'},
    { id: '21AAP', district: 'West Siang', state: 'Arunachal Pradesh', pincode: '791125'},

    { id: '3', district: 'Baksa', state: 'Assam', pincode: '781372'},
    { id: '3AS', district: 'Barpeta', state: 'Assam', pincode: '781301'},
    { id: '4AS', district: 'Biswanath', state: 'Assam', pincode: '784176'},
    { id: '5AS', district: 'Bongaigaon', state: 'Assam', pincode: '783380'},
    { id: '6AS', district: 'Cachar', state: 'Assam', pincode: '788001'},
    { id: '7AS', district: 'Charaideo', state: 'Assam', pincode: '782445'},
    { id: '8AS', district: 'Chirang', state: 'Assam', pincode: '783390'},
    { id: '9AS', district: 'Darrang', state: 'Assam', pincode: '784148'},
    { id: '10AS', district: 'Dhemaji', state: 'Assam', pincode: '787057'},
    { id: '11AS', district: 'Dhubri', state: 'Assam', pincode: '783301'},
    { id: '12AS', district: 'Dibrugarh', state: 'Assam', pincode: '786001'},
    { id: '13AS', district: 'Dima Hasao (North Cachar Hills)', state: 'Assam', pincode: '788819'},
    { id: '14AS', district: 'Goalpara', state: 'Assam', pincode: '783101'},
    { id: '15AS', district: 'Golaghat', state: 'Assam', pincode: '785621'},
    { id: '16AS', district: 'Hailakandi', state: 'Assam', pincode: '788151'},
    { id: '17AS', district: 'Hojai', state: 'Assam', pincode: '782435'},
    { id: '19AS', district: 'Jorhat', state: 'Assam', pincode: '785001'},
    { id: '20AS', district: 'Kamrup', state: 'Assam', pincode: '781001'},
    { id: '21AS', district: 'Kamrup Metropolitan', state: 'Assam', pincode: '781022'},
    { id: '22AS', district: 'Karbi Anglong', state: 'Assam', pincode: '782460'},
    { id: '23AS', district: 'Karimganj', state: 'Assam', pincode: '788710'},
    { id: '24AS', district: 'Kokrajhar', state: 'Assam', pincode: '783370'},
    { id: '25AS', district: 'Lakhimpur', state: 'Assam', pincode: '787001'},
    { id: '26AS', district: 'Majuli', state: 'Assam', pincode: '785105'},
    { id: '27AS', district: 'Morigaon', state: 'Assam', pincode: '782105'},
    { id: '27AS', district: 'Nagaon', state: 'Assam', pincode: '782001'},
    { id: '27AS', district: 'Nalbari', state: 'Assam', pincode: '781335'},


    { id: '4', district: 'Araria', state: 'Bihar', pincode: '', landmark: ''},
    { id: '4BH', district: '', state: 'Bihar', pincode: '', landmark: ''},
    { id: '5BH', district: '', state: 'Bihar', pincode: '', landmark: ''},
    { id: '6BH', district: '', state: 'Bihar', pincode: '', landmark: ''},
    { id: '7BH', district: '', state: 'Bihar', pincode: '', landmark: ''},
    { id: '8BH', district: '', state: 'Bihar', pincode: '', landmark: ''},
    { id: '9BH', district: '', state: 'Bihar', pincode: '', landmark: ''},
    { id: '10BH', district: '', state: 'Bihar', pincode: '', landmark: ''},
    { id: '4', district: '', state: 'Bihar', pincode: '', landmark: ''},
    { id: '4', district: '', state: 'Bihar', pincode: '', landmark: ''},
    { id: '4', district: '', state: 'Bihar', pincode: '', landmark: ''},
    { id: '4', district: '', state: 'Bihar', pincode: '', landmark: ''},
    { id: '4', district: '', state: 'Bihar', pincode: '', landmark: ''},
    { id: '4', district: '', state: 'Bihar', pincode: '', landmark: ''},
    { id: '4', district: '', state: 'Bihar', pincode: '', landmark: ''},
    { id: '4', district: '', state: 'Bihar', pincode: '', landmark: ''},
    { id: '4', district: '', state: 'Bihar', pincode: '', landmark: ''},
    { id: '4', district: '', state: 'Bihar', pincode: '', landmark: ''},
    { id: '4', district: '', state: 'Bihar', pincode: '', landmark: ''},
    { id: '4', district: '', state: 'Bihar', pincode: '', landmark: ''},
    { id: '4', district: '', state: 'Bihar', pincode: '', landmark: ''},
    { id: '4', district: '', state: 'Bihar', pincode: '', landmark: ''},


    { id: '5', district: '', state: 'Chhattishgarh', pincode: '', landmark: ''},
    { id: '6', district: '', state: 'Goa', pincode: '', landmark: ''},
    { id: '7', district: '', state: 'Gujarat', pincode: '', landmark: ''},
    { id: '8', district: '', state: 'Haryana', pincode: '', landmark: ''},
    { id: '9', district: '', state: 'Himanchal Pradesh', pincode: '', landmark: ''},
    { id: '10', district: '', state: 'Jammu & Kashmir', pincode: '', landmark: ''},
    { id: '11', district: '', state: 'Jharkhand', pincode: '', landmark: ''},
    { id: '12', district: '', state: 'Karnataka', pincode: '', landmark: ''},
    { id: '13', district: '', state: 'Kerala', pincode: '', landmark: ''},
    { id: '14', district: '', state: 'Madhya Pradesh', pincode: '', landmark: ''},
    { id: '15', district: '', state: 'Maharashtra', pincode: '', landmark: ''},
    { id: '16', district: '', state: 'Manipur', pincode: '', landmark: ''},
    { id: '17', district: '', state: 'Meghalaya', pincode: '', landmark: ''},
    { id: '18', district: '', state: 'Mizoram', pincode: '', landmark: ''},
    { id: '19', district: '', state: 'Nagaland', pincode: '', landmark: ''},
    { id: '20', district: '', state: 'Odisha', pincode: '', landmark: ''},
    { id: '21', district: '', state: 'Punjab', pincode: '', landmark: ''},
    { id: '22', district: '', state: 'Rajasthan', pincode: '', landmark: ''},
    { id: '23', district: '', state: 'Sikkim', pincode: '', landmark: ''},
    { id: '24', district: '', state: 'Tamil Nadu', pincode: '', landmark: ''},
    { id: '25', district: '', state: 'Telangana', pincode: '', landmark: ''},
    { id: '26', district: '', state: 'Tripura', pincode: '', landmark: ''},
    { id: '27', district: '', state: 'Uttar Pradesh', pincode: '', landmark: ''},
    { id: '28', district: '', state: 'Uttarakhand', pincode: '', landmark: ''},
    { id: '29', district: '', state: 'West Bengal', pincode: '', landmark: ''},
]