// const dt = {
//   message: "Explore New App Intake",
//   access: true,
//   data_set: [
//     {
//       name: "October",
//       value: {
//         total_intake: 0,
//         cap_intake: 0,
//         il_intake: 0,
//         ad_th_cap: 0,
//         ad_th_ag_cap: 0,
//         ad_th_il: 0,
//         ad_th_ews: 0,
//         ad_th_tfws: 0,
//         grand_total: 0,
//       },
//       _id: "651bd18ae39dbdf817dd5a6c",
//     },
//     {
//       name: "January 2024",
//       value: {
//         total_intake: 0,
//         cap_intake: 0,
//         il_intake: 0,
//         ad_th_cap: 0,
//         ad_th_ag_cap: 0,
//         ad_th_il: 0,
//         ad_th_ews: 0,
//         ad_th_tfws: 0,
//         grand_total: 0,
//       },
//       _id: "65923f900dfe392501c6f48e",
//     },
//     {
//       name: "3rd Jan Admission Testing",
//       value: {
//         total_intake: 0,
//         cap_intake: 0,
//         il_intake: 0,
//         ad_th_cap: 0,
//         ad_th_ag_cap: 0,
//         ad_th_il: 0,
//         ad_th_ews: 0,
//         ad_th_tfws: 0,
//         grand_total: 0,
//       },
//       _id: "6594d1354f9c23945c5151fe",
//     },
//     {
//       name: "3rd Jan Admission Testing 2",
//       value: {
//         total_intake: 0,
//         cap_intake: 0,
//         il_intake: 0,
//         ad_th_cap: 0,
//         ad_th_ag_cap: 0,
//         ad_th_il: 0,
//         ad_th_ews: 0,
//         ad_th_tfws: 0,
//         grand_total: 0,
//       },
//       _id: "6594d4f74f9c23945c515653",
//     },
//     {
//       name: "Admission Fees Application",
//       value: {
//         total_intake: 0,
//         cap_intake: 0,
//         il_intake: 0,
//         ad_th_cap: 0,
//         ad_th_ag_cap: 0,
//         ad_th_il: 0,
//         ad_th_ews: 0,
//         ad_th_tfws: 0,
//         grand_total: 0,
//       },
//       _id: "659953fad344411decadd676",
//     },
//     {
//       name: "With Complete",
//       value: {
//         total_intake: 0,
//         cap_intake: 0,
//         il_intake: 0,
//         ad_th_cap: 0,
//         ad_th_ag_cap: 0,
//         ad_th_il: 0,
//         ad_th_ews: 0,
//         ad_th_tfws: 0,
//         grand_total: 0,
//       },
//       _id: "659966aa145286ef0c61c7f2",
//     },
//     {
//       name: "7th Jan Admission Testing",
//       value: {
//         total_intake: 0,
//         cap_intake: 0,
//         il_intake: 0,
//         ad_th_cap: 0,
//         ad_th_ag_cap: 0,
//         ad_th_il: 0,
//         ad_th_ews: 0,
//         ad_th_tfws: 0,
//         grand_total: 0,
//       },
//       _id: "659a3e27f485e4db3c83fae7",
//     },
//     {
//       name: "Direct Admission testing",
//       value: {
//         total_intake: 0,
//         cap_intake: 0,
//         il_intake: 0,
//         ad_th_cap: 0,
//         ad_th_ag_cap: 0,
//         ad_th_il: 0,
//         ad_th_ews: 0,
//         ad_th_tfws: 0,
//         grand_total: 0,
//       },
//       _id: "659b7846d4c730cd0653ecdc",
//     },
//     {
//       name: "January Application",
//       value: {
//         total_intake: 0,
//         cap_intake: 0,
//         il_intake: 0,
//         ad_th_cap: 0,
//         ad_th_ag_cap: 0,
//         ad_th_il: 0,
//         ad_th_ews: 0,
//         ad_th_tfws: 0,
//         grand_total: 0,
//       },
//       _id: "659c448340b0e3624a5586c3",
//     },
//     {
//       name: "Jan Direct",
//       value: {
//         total_intake: 0,
//         cap_intake: 0,
//         il_intake: 0,
//         ad_th_cap: 0,
//         ad_th_ag_cap: 0,
//         ad_th_il: 0,
//         ad_th_ews: 0,
//         ad_th_tfws: 0,
//         grand_total: 0,
//       },
//       _id: "659dfb1681d06f32e33ba771",
//     },
//     {
//       name: "Department of Computer Science Application",
//       value: {
//         total_intake: 0,
//         cap_intake: 0,
//         il_intake: 0,
//         ad_th_cap: 0,
//         ad_th_ag_cap: 0,
//         ad_th_il: 0,
//         ad_th_ews: 0,
//         ad_th_tfws: 0,
//         grand_total: 0,
//       },
//       _id: "659e92ae81d06f32e33be50e",
//     },
//     {
//       name: "FY B.Tech Mechanical 2024-25",
//       value: {
//         total_intake: 0,
//         cap_intake: 0,
//         il_intake: 0,
//         ad_th_cap: 0,
//         ad_th_ag_cap: 0,
//         ad_th_il: 0,
//         ad_th_ews: 0,
//         ad_th_tfws: 0,
//         grand_total: 0,
//       },
//       _id: "65a76ffa33d934f12548c982",
//     },
//     {
//       name: "Z-Application",
//       value: {
//         total_intake: 0,
//         cap_intake: 0,
//         il_intake: 0,
//         ad_th_cap: 0,
//         ad_th_ag_cap: 0,
//         ad_th_il: 0,
//         ad_th_ews: 0,
//         ad_th_tfws: 0,
//         grand_total: 0,
//       },
//       _id: "663524f53c96d93964c46a89",
//     },
//     {
//       name: "Y-Group",
//       value: {
//         total_intake: 0,
//         cap_intake: 0,
//         il_intake: 0,
//         ad_th_cap: 0,
//         ad_th_ag_cap: 0,
//         ad_th_il: 0,
//         ad_th_ews: 0,
//         ad_th_tfws: 0,
//         grand_total: 0,
//       },
//       _id: "663d7a7da1e59b22b1aad9b8",
//     },
//     {
//       name: "X- Application",
//       value: {
//         total_intake: 0,
//         cap_intake: 0,
//         il_intake: 0,
//         ad_th_cap: 0,
//         ad_th_ag_cap: 0,
//         ad_th_il: 0,
//         ad_th_ews: 0,
//         ad_th_tfws: 0,
//         grand_total: 0,
//       },
//       _id: "6642f7c682af2a2110f48216",
//     },
//     {
//       name: "W-Application",
//       value: {
//         total_intake: 0,
//         cap_intake: 0,
//         il_intake: 0,
//         ad_th_cap: 0,
//         ad_th_ag_cap: 0,
//         ad_th_il: 0,
//         ad_th_ews: 0,
//         ad_th_tfws: 0,
//         grand_total: 0,
//       },
//       _id: "66430275e4fd9704e3868334",
//     },
//     {
//       name: "D-Application",
//       value: {
//         total_intake: 0,
//         cap_intake: 0,
//         il_intake: 0,
//         ad_th_cap: 0,
//         ad_th_ag_cap: 0,
//         ad_th_il: 0,
//         ad_th_ews: 0,
//         ad_th_tfws: 0,
//         grand_total: 0,
//       },
//       _id: "664389cf6c466fea5e379792",
//     },
//     {
//       name: "FYBSC 2024-25",
//       value: {
//         total_intake: 0,
//         cap_intake: 0,
//         il_intake: 0,
//         ad_th_cap: 0,
//         ad_th_ag_cap: 0,
//         ad_th_il: 0,
//         ad_th_ews: 0,
//         ad_th_tfws: 0,
//         grand_total: 0,
//       },
//       _id: "66445cf4fb698cecac294bdc",
//     },
//     {
//       name: "FYBSC Regular",
//       value: {
//         total_intake: 0,
//         cap_intake: 0,
//         il_intake: 0,
//         ad_th_cap: 0,
//         ad_th_ag_cap: 0,
//         ad_th_il: 0,
//         ad_th_ews: 0,
//         ad_th_tfws: 0,
//         grand_total: 0,
//       },
//       _id: "6652ecc0aca6fc1ea555ca0a",
//     },
//     {
//       name: "Test All Form Fields",
//       value: {
//         total_intake: 0,
//         cap_intake: 0,
//         il_intake: 0,
//         ad_th_cap: 0,
//         ad_th_ag_cap: 0,
//         ad_th_il: 0,
//         ad_th_ews: 0,
//         ad_th_tfws: 0,
//         grand_total: 0,
//       },
//       _id: "66536cfb2632987a7ba47e57",
//     },
//     {
//       name: "Test All Form Fields 2",
//       value: {
//         total_intake: 0,
//         cap_intake: 0,
//         il_intake: 0,
//         ad_th_cap: 0,
//         ad_th_ag_cap: 0,
//         ad_th_il: 0,
//         ad_th_ews: 0,
//         ad_th_tfws: 0,
//         grand_total: 0,
//       },
//       _id: "665370413d9b63fbb1c2fcd2",
//     },
//     {
//       name: "Test All Form Fields 3",
//       value: {
//         total_intake: 0,
//         cap_intake: 0,
//         il_intake: 0,
//         ad_th_cap: 0,
//         ad_th_ag_cap: 0,
//         ad_th_il: 0,
//         ad_th_ews: 0,
//         ad_th_tfws: 0,
//         grand_total: 0,
//       },
//       _id: "665372ed7d4ac8fdff74ae0f",
//     },
//     {
//       name: "Test1",
//       value: {
//         total_intake: 0,
//         cap_intake: 0,
//         il_intake: 0,
//         ad_th_cap: 0,
//         ad_th_ag_cap: 0,
//         ad_th_il: 0,
//         ad_th_ews: 0,
//         ad_th_tfws: 0,
//         grand_total: 0,
//       },
//       _id: "665566b12e9699101d68a925",
//     },
//     {
//       name: "Subject Validation",
//       value: {
//         total_intake: 0,
//         cap_intake: 0,
//         il_intake: 0,
//         ad_th_cap: 0,
//         ad_th_ag_cap: 0,
//         ad_th_il: 0,
//         ad_th_ews: 0,
//         ad_th_tfws: 0,
//         grand_total: 0,
//       },
//       _id: "6656290c3e20a3f34c6313cd",
//     },
//     {
//       name: "10 June 2024",
//       value: {
//         total_intake: 0,
//         cap_intake: 0,
//         il_intake: 0,
//         ad_th_cap: 0,
//         ad_th_ag_cap: 0,
//         ad_th_il: 0,
//         ad_th_ews: 0,
//         ad_th_tfws: 0,
//         grand_total: 0,
//       },
//       _id: "66668fd68a2eeeae16db6d98",
//     },
//     {
//       name: "BSC - Application",
//       value: {
//         total_intake: 0,
//         cap_intake: 0,
//         il_intake: 0,
//         ad_th_cap: 0,
//         ad_th_ag_cap: 0,
//         ad_th_il: 0,
//         ad_th_ews: 0,
//         ad_th_tfws: 0,
//         grand_total: 0,
//       },
//       _id: "666926198a2eeeae16dcc3ce",
//     },
//     {
//       name: "17-June-2024",
//       value: {
//         total_intake: 200,
//         cap_intake: 12,
//         il_intake: 340,
//         ad_th_cap: 0,
//         ad_th_ag_cap: 0,
//         ad_th_il: 0,
//         ad_th_ews: 1,
//         ad_th_tfws: 0,
//         grand_total: 553,
//       },
//       _id: "666fee7a1eee93733cc5edf2",
//     },
//     {
//       name: "FY 2nd Scholarship",
//       value: {
//         total_intake: 0,
//         cap_intake: 0,
//         il_intake: 0,
//         ad_th_cap: 0,
//         ad_th_ag_cap: 0,
//         ad_th_il: 0,
//         ad_th_ews: 0,
//         ad_th_tfws: 0,
//         grand_total: 0,
//       },
//       _id: "668a8b49d46d60460840dacc",
//     },
//     {
//       name: "SY 2nd Scholarship",
//       value: {
//         total_intake: 0,
//         cap_intake: 0,
//         il_intake: 0,
//         ad_th_cap: 0,
//         ad_th_ag_cap: 0,
//         ad_th_il: 0,
//         ad_th_ews: 0,
//         ad_th_tfws: 0,
//         grand_total: 0,
//       },
//       _id: "668a8b5bd46d60460840db90",
//     },
//     {
//       name: "FY 1st Scholarship",
//       value: {
//         total_intake: 0,
//         cap_intake: 0,
//         il_intake: 0,
//         ad_th_cap: 0,
//         ad_th_ag_cap: 0,
//         ad_th_il: 0,
//         ad_th_ews: 0,
//         ad_th_tfws: 0,
//         grand_total: 0,
//       },
//       _id: "668a8b72d46d60460840dd70",
//     },
//     {
//       name: "SY 1st Scholarship",
//       value: {
//         total_intake: 0,
//         cap_intake: 0,
//         il_intake: 0,
//         ad_th_cap: 0,
//         ad_th_ag_cap: 0,
//         ad_th_il: 0,
//         ad_th_ews: 0,
//         ad_th_tfws: 0,
//         grand_total: 0,
//       },
//       _id: "668a8b80d46d60460840dea2",
//     },
//     {
//       name: "13 July 2024",
//       value: {
//         ad_th_ag_cap: 1,
//         ad_th_cap: 1,
//         ad_th_ews: 0,
//         ad_th_il: 0,
//         ad_th_tfws: 0,
//         cap_intake: 12,
//         grand_total: 124,
//         il_intake: 10,
//         total_intake: 100,
//       },
//       _id: "6691dc75556be5f248cba652",
//     },
//   ],
//   ads_admin: {
//     _id: "651ba22de39dbdf817dd520c",
//     insName: "Allahabad Central University (ACU)",
//     name: "ald_acu",
//     insState: "",
//     insDistrict: "",
//     insPincode: 234567,
//     insAddress: "Prayagraj, Uttar Pradesh India",
//     photoId: "0",
//     insProfilePhoto: "233f3b520ee3187f0fd4e64791562bda",
//     insAffiliated: "Central University",
//     affliatedLogo: "92f4dfbfaafe41cc60ddd0d618337c62",
//   },
//   level: "info",
// };

const dt = {
    message: "Explore New App Intake",
    access: true,
    data_set: [
      {
        name: "Test All Form Fields",
        value: {
          total_intake: 0,
          cap_intake: 0,
          il_intake: 0,
          ad_th_cap: 0,
          ad_th_ag_cap: 0,
          ad_th_il: 0,
          ad_th_ews: 0,
          ad_th_tfws: 0,
          grand_total: 0,
        },
        _id: "66536cfb2632987a7ba47e57",
      },
      {
        name: "Subject Validation",
        value: {
          total_intake: 0,
          cap_intake: 0,
          il_intake: 0,
          ad_th_cap: 0,
          ad_th_ag_cap: 0,
          ad_th_il: 0,
          ad_th_ews: 0,
          ad_th_tfws: 0,
          grand_total: 0,
        },
        _id: "6656290c3e20a3f34c6313cd",
      },
      null,
      null,
    ],
    ads_admin: {
      _id: "651ba22de39dbdf817dd520c",
      insName: "Allahabad Central University (ACU)",
      name: "ald_acu",
      insState: "",
      insDistrict: "",
      insPincode: 234567,
      insAddress: "Prayagraj, Uttar Pradesh India",
      photoId: "0",
      insProfilePhoto: "233f3b520ee3187f0fd4e64791562bda",
      insAffiliated: "Central University",
      affliatedLogo: "92f4dfbfaafe41cc60ddd0d618337c62",
    },
    batch: "U-2024-25",
    level: "info",
  };
  
  const admissionIntakeQuery = async (admissionId, batchId) => {
    // here write your function
  };
  const admissionIntakeReportData = async (admissionId = "", batchId = "") => {
    // const dt = await admissionIntakeQuery(admissionId, batchId);
    return { dt };
  };
  module.exports = admissionIntakeReportData;
  
  