module.exports.academic_form = [
    {
        section_name: "Academic Details",
        section_visibilty: true,
        section_key: "academic_details",
        form_checklist: [ 
            {
                form_checklist_name: "Std 10th Details",
                form_checklist_key: "std_tenth_details",
                form_checklist_visibility: true,
                form_checklist_placeholder: "Enter Std 10th Details",
                form_checklist_lable: "",
                form_checklist_typo: "CHECKBOX",
                form_checklist_sample: "Std 10th Details",
                form_checklist_typo_option_pl: ["Std 10th Details"],
                nested_form_checklist: [
                    {
                        form_checklist_name: "Month of Passing",
                        form_checklist_key: "month_of_passing",
                        form_checklist_visibility: true,
                        form_checklist_placeholder: "Enter Month of Passing",
                        form_checklist_lable: "Enter Month of Passing",
                        form_checklist_typo: "TEXT",
                        form_checklist_sample: "Month of Passing",
                        form_checklist_typo_option_pl: [],
                    },
                    {
                        form_checklist_name: "Year of Passing",
                        form_checklist_key: "year_of_passing",
                        form_checklist_visibility: true,
                        form_checklist_placeholder: "Enter Year of Passing",
                        form_checklist_lable: "Enter Year of Passing",
                        form_checklist_typo: "TEXT",
                        form_checklist_sample: "Year of Passing",
                        form_checklist_typo_option_pl: [],
                    },
                    {
                        form_checklist_name: "Percentage",
                        form_checklist_key: "percentage",
                        form_checklist_visibility: true,
                        form_checklist_placeholder: "Enter Percentage",
                        form_checklist_lable: "Enter Percentage",
                        form_checklist_typo: "NUMBER",
                        form_checklist_sample: "Percentage",
                        form_checklist_typo_option_pl: [],
                    },
                    {
                        form_checklist_name: "Name of Institute",
                        form_checklist_key: "name_of_institute",
                        form_checklist_visibility: true,
                        form_checklist_placeholder: "Enter Name of Institute",
                        form_checklist_lable: "Enter Name of Institute",
                        form_checklist_typo: "TEXT",
                        form_checklist_sample: "Name of Institute",
                        form_checklist_typo_option_pl: [],
                    }
                ]
            },
            {
                form_checklist_name: "HSC (10+2) / Diploma",
                form_checklist_key: "hsc_diploma",
                form_checklist_visibility: true,
                form_checklist_placeholder: "Enter HSC (10+2) / Diploma",
                form_checklist_lable: "",
                form_checklist_typo: "CHECKBOX",
                form_checklist_sample: "HSC (10+2) / Diploma",
                form_checklist_typo_option_pl: ["HSC (10+2) / Diploma"],
                nested_form_checklist: [
                    {
                        form_checklist_name: "Month",
                        form_checklist_key: "hsc_month",
                        form_checklist_visibility: true,
                        form_checklist_placeholder: "Enter Month",
                        form_checklist_lable: "Enter Month",
                        form_checklist_typo: "TEXT",
                        form_checklist_sample: "Month",
                        form_checklist_typo_option_pl: [],
                    },
                    {
                        form_checklist_name: "Year",
                        form_checklist_key: "hsc_year",
                        form_checklist_visibility: true,
                        form_checklist_placeholder: "Enter Year",
                        form_checklist_lable: "Enter Year",
                        form_checklist_typo: "TEXT",
                        form_checklist_sample: "Year",
                        form_checklist_typo_option_pl: [],
                    },
                    {
                        form_checklist_name: "Percentage",
                        form_checklist_key: "hsc_percentage",
                        form_checklist_visibility: true,
                        form_checklist_placeholder: "Enter Percentage",
                        form_checklist_lable: "Enter Percentage",
                        form_checklist_typo: "NUMBER",
                        form_checklist_sample: "Percentage",
                        form_checklist_typo_option_pl: [],
                    },
                    {
                        form_checklist_name: "Name of Institute",
                        form_checklist_key: "hsc_name_of_institute",
                        form_checklist_visibility: true,
                        form_checklist_placeholder: "Enter Name of Institute",
                        form_checklist_lable: "Enter Name of Institute",
                        form_checklist_typo: "TEXT",
                        form_checklist_sample: "Name of Institute",
                        form_checklist_typo_option_pl: [],
                    },
                    {
                        form_checklist_name: "Board",
                        form_checklist_key: "hsc_board",
                        form_checklist_visibility: true,
                        form_checklist_placeholder: "Enter Board",
                        form_checklist_lable: "Enter Board",
                        form_checklist_typo: "TEXT",
                        form_checklist_sample: "Board",
                        form_checklist_typo_option_pl: [],
                    }
                ]
            },
            {
                form_checklist_name: "UG For Engineering",
                form_checklist_key: "ug_engineering",
                form_checklist_visibility: true,
                form_checklist_placeholder: "Enter UG For Engineering",
                form_checklist_lable: "",
                form_checklist_typo: "CHECKBOX",
                form_checklist_sample: "UG For Engineering",
                form_checklist_typo_option_pl: ["UG For Engineering"],
                nested_form_checklist: [
                    {
                        form_checklist_name: "Pre-final Sem",
                        form_checklist_key: "pre_final_sem",
                        form_checklist_visibility: true,
                        form_checklist_placeholder: "Enter Pre-final Sem",
                        form_checklist_lable: "",
                        form_checklist_typo: "CHECKBOX",
                        form_checklist_sample: "Pre-final Sem",
                        form_checklist_typo_option_pl: ["Pre-final Sem"],
                        nested_form_checklist_nested: [
                            {
                                form_checklist_name: "Marks / Credits Obtain",
                                form_checklist_key: "pre_marks_credit_obtain",
                                form_checklist_visibility: true,
                                form_checklist_placeholder: "Enter Marks / Credits Obtain",
                                form_checklist_lable: "Enter Marks / Credits Obtain",
                                form_checklist_typo: "NUMBER",
                                form_checklist_sample: "Marks / Credits Obtain",
                                form_checklist_typo_option_pl: [],
                            },
                            {
                                form_checklist_name: "Total Grade Points",
                                form_checklist_key: "pre_total_grade_points",
                                form_checklist_visibility: true,
                                form_checklist_placeholder: "Enter Total Grade Points",
                                form_checklist_lable: "Enter Total Grade Points",
                                form_checklist_typo: "NUMBER",
                                form_checklist_sample: "Total Grade Points",
                                form_checklist_typo_option_pl: [],
                            },
                        ]
                    },
                    {
                        form_checklist_name: "Final Sem / Year",
                        form_checklist_key: "final_sem",
                        form_checklist_visibility: true,
                        form_checklist_placeholder: "Enter Final Sem / Year",
                        form_checklist_lable: "",
                        form_checklist_typo: "CHECKBOX",
                        form_checklist_sample: "Final Sem / Year",
                        form_checklist_typo_option_pl: ["Final Sem / Year"],
                        nested_form_checklist_nested: [
                            {
                                form_checklist_name: "Marks / Credits Obtain",
                                form_checklist_key: "final_marks_credit_obtain",
                                form_checklist_visibility: true,
                                form_checklist_placeholder: "Enter Marks / Credits Obtain",
                                form_checklist_lable: "Enter Marks / Credits Obtain",
                                form_checklist_typo: "NUMBER",
                                form_checklist_sample: "Marks / Credits Obtain",
                                form_checklist_typo_option_pl: [],
                            },
                            {
                                form_checklist_name: "Total Grade Points",
                                form_checklist_key: "final_total_grade_points",
                                form_checklist_visibility: true,
                                form_checklist_placeholder: "Enter Total Grade Points",
                                form_checklist_lable: "Enter Total Grade Points",
                                form_checklist_typo: "NUMBER",
                                form_checklist_sample: "Total Grade Points",
                                form_checklist_typo_option_pl: [],
                            },
                            {
                                form_checklist_name: "CPI",
                                form_checklist_key: "final_cpi",
                                form_checklist_visibility: true,
                                form_checklist_placeholder: "Enter CPI",
                                form_checklist_lable: "Enter CPI",
                                form_checklist_typo: "NUMBER",
                                form_checklist_sample: "CPI",
                                form_checklist_typo_option_pl: [],
                            },
                        ]
                    }
                ]
            },
            {
                form_checklist_name: "Entrance Exam",
                form_checklist_key: "entrance_exam",
                form_checklist_visibility: true,
                form_checklist_placeholder: "Enter Entrance Exam",
                form_checklist_lable: "",
                form_checklist_typo: "CHECKBOX",
                form_checklist_sample: "Entrance Exam",
                form_checklist_typo_option_pl: ["Entrance Exam"],
                nested_form_checklist: [
                    {
                        form_checklist_name: "JEE Details",
                        form_checklist_key: "jee_details",
                        form_checklist_visibility: true,
                        form_checklist_placeholder: "Enter JEE Details",
                        form_checklist_lable: "",
                        form_checklist_typo: "CHECKBOX",
                        form_checklist_sample: "JEE Details",
                        form_checklist_typo_option_pl: ["JEE Details"],
                        nested_form_checklist_nested: [
                            {
                                form_checklist_name: "ROLL No.",
                                form_checklist_key: "jee_rollno",
                                form_checklist_visibility: true,
                                form_checklist_placeholder: "Enter ROLL No.",
                                form_checklist_lable: "Enter ROLL No.",
                                form_checklist_typo: "TEXT",
                                form_checklist_sample: "ROLL No.",
                                form_checklist_typo_option_pl: [],
                            },
                            {
                                form_checklist_name: "Physics Marks Obtained",
                                form_checklist_key: "jee_physics_marks",
                                form_checklist_visibility: true,
                                form_checklist_placeholder: "Enter Physics Marks Obtained",
                                form_checklist_lable: "Enter Physics Marks Obtained",
                                form_checklist_typo: "NUMBER",
                                form_checklist_sample: "Physics Marks Obtained",
                                form_checklist_typo_option_pl: [],
                            },
                            {
                                form_checklist_name: "Chemistry Marks Obtained",
                                form_checklist_key: "jee_chemistry_marks",
                                form_checklist_visibility: true,
                                form_checklist_placeholder: "Enter Chemistry Marks Obtained",
                                form_checklist_lable: "Enter Chemistry Marks Obtained",
                                form_checklist_typo: "NUMBER",
                                form_checklist_sample: "Chemistry Marks Obtained",
                                form_checklist_typo_option_pl: [],
                            },
                            {
                                form_checklist_name: "Mathematics Marks Obtained",
                                form_checklist_key: "jee_mathematics_marks",
                                form_checklist_visibility: true,
                                form_checklist_placeholder: "Enter Mathematics Marks Obtained",
                                form_checklist_lable: "Enter Mathematics Marks Obtained",
                                form_checklist_typo: "NUMBER",
                                form_checklist_sample: "Mathematics Marks Obtained",
                                form_checklist_typo_option_pl: [],
                            },
                            {
                                form_checklist_name: "JEE Total",
                                form_checklist_key: "jee_total",
                                form_checklist_visibility: true,
                                form_checklist_placeholder: "Enter JEE Total",
                                form_checklist_lable: "Enter JEE Total",
                                form_checklist_typo: "NUMBER",
                                form_checklist_sample: "JEE Total",
                                form_checklist_typo_option_pl: [],
                            },
                            {
                                form_checklist_name: "JEE Percentile",
                                form_checklist_key: "jee_percentile",
                                form_checklist_visibility: true,
                                form_checklist_placeholder: "Enter JEE Percentile",
                                form_checklist_lable: "Enter JEE Percentile",
                                form_checklist_typo: "NUMBER",
                                form_checklist_sample: "JEE Percentile",
                                form_checklist_typo_option_pl: [],
                            }
                        ]
                    },
                    {
                        form_checklist_name: "CET Details",
                        form_checklist_key: "cet_details",
                        form_checklist_visibility: true,
                        form_checklist_placeholder: "Enter CET Details",
                        form_checklist_lable: "",
                        form_checklist_typo: "CHECKBOX",
                        form_checklist_sample: "CET Details",
                        form_checklist_typo_option_pl: ["CET Details"],
                        nested_form_checklist_nested: [
                            {
                                form_checklist_name: "ROLL No.",
                                form_checklist_key: "cet_rollno",
                                form_checklist_visibility: true,
                                form_checklist_placeholder: "Enter ROLL No.",
                                form_checklist_lable: "Enter ROLL No.",
                                form_checklist_typo: "TEXT",
                                form_checklist_sample: "ROLL No.",
                                form_checklist_typo_option_pl: [],
                            },
                            {
                                form_checklist_name: "Physics Marks Obtained",
                                form_checklist_key: "cet_physics_marks",
                                form_checklist_visibility: true,
                                form_checklist_placeholder: "Enter Physics Marks Obtained",
                                form_checklist_lable: "Enter Physics Marks Obtained",
                                form_checklist_typo: "NUMBER",
                                form_checklist_sample: "Physics Marks Obtained",
                                form_checklist_typo_option_pl: [],
                            },
                            {
                                form_checklist_name: "Chemistry Marks Obtained",
                                form_checklist_key: "cet_chemistry_marks",
                                form_checklist_visibility: true,
                                form_checklist_placeholder: "Enter Chemistry Marks Obtained",
                                form_checklist_lable: "Enter Chemistry Marks Obtained",
                                form_checklist_typo: "NUMBER",
                                form_checklist_sample: "Chemistry Marks Obtained",
                                form_checklist_typo_option_pl: [],
                            },
                            {
                                form_checklist_name: "Mathematics Marks Obtained",
                                form_checklist_key: "cet_mathematics_marks",
                                form_checklist_visibility: true,
                                form_checklist_placeholder: "Enter Mathematics Marks Obtained",
                                form_checklist_lable: "Enter Mathematics Marks Obtained",
                                form_checklist_typo: "NUMBER",
                                form_checklist_sample: "Mathematics Marks Obtained",
                                form_checklist_typo_option_pl: [],
                            },
                            {
                                form_checklist_name: "Biology Marks Obtained",
                                form_checklist_key: "cet_biology_marks",
                                form_checklist_visibility: true,
                                form_checklist_placeholder: "Enter Biology Marks Obtained",
                                form_checklist_lable: "Enter Biology Marks Obtained",
                                form_checklist_typo: "NUMBER",
                                form_checklist_sample: "Biology Marks Obtained",
                                form_checklist_typo_option_pl: [],
                            }
                        ]
                    },
                    {
                        form_checklist_name: "AIEEE Details",
                        form_checklist_key: "aieee_details",
                        form_checklist_visibility: true,
                        form_checklist_placeholder: "Enter AIEEE Details",
                        form_checklist_lable: "",
                        form_checklist_typo: "CHECKBOX",
                        form_checklist_sample: "AIEEE Details",
                        form_checklist_typo_option_pl: ["AIEEE Details"],
                        nested_form_checklist_nested: [
                            {
                                form_checklist_name: "ROLL No.",
                                form_checklist_key: "aieee_rollno",
                                form_checklist_visibility: true,
                                form_checklist_placeholder: "Enter ROLL No.",
                                form_checklist_lable: "Enter ROLL No.",
                                form_checklist_typo: "TEXT",
                                form_checklist_sample: "ROLL No.",
                                form_checklist_typo_option_pl: [],
                            },
                            {
                                form_checklist_name: "Physics Marks Obtained",
                                form_checklist_key: "aieee_physics_marks",
                                form_checklist_visibility: true,
                                form_checklist_placeholder: "Enter Physics Marks Obtained",
                                form_checklist_lable: "Enter Physics Marks Obtained",
                                form_checklist_typo: "NUMBER",
                                form_checklist_sample: "Physics Marks Obtained",
                                form_checklist_typo_option_pl: [],
                            },
                            {
                                form_checklist_name: "Chemistry Marks Obtained",
                                form_checklist_key: "aieee_chemistry_marks",
                                form_checklist_visibility: true,
                                form_checklist_placeholder: "Enter Chemistry Marks Obtained",
                                form_checklist_lable: "Enter Chemistry Marks Obtained",
                                form_checklist_typo: "NUMBER",
                                form_checklist_sample: "Chemistry Marks Obtained",
                                form_checklist_typo_option_pl: [],
                            },
                            {
                                form_checklist_name: "Mathematics Marks Obtained",
                                form_checklist_key: "aieee_mathematics_marks",
                                form_checklist_visibility: true,
                                form_checklist_placeholder: "Enter Mathematics Marks Obtained",
                                form_checklist_lable: "Enter Mathematics Marks Obtained",
                                form_checklist_typo: "NUMBER",
                                form_checklist_sample: "Mathematics Marks Obtained",
                                form_checklist_typo_option_pl: [],
                            },
                            {
                                form_checklist_name: "Biology Marks Obtained",
                                form_checklist_key: "aieee_biology_marks",
                                form_checklist_visibility: true,
                                form_checklist_placeholder: "Enter Biology Marks Obtained",
                                form_checklist_lable: "Enter Biology Marks Obtained",
                                form_checklist_typo: "NUMBER",
                                form_checklist_sample: "Biology Marks Obtained",
                                form_checklist_typo_option_pl: [],
                            }
                        ]
                    }
                ]
            },
        ]
    }
]