module.exports.academic_form = [
    {
        section_name: "Academic Details",
        section_visibilty: true,
        section_key: "academic_details",
        form_checklist: [ 
            {
                form_checklist_name: "Std 10th Details",
                form_checklist_key: "std_tenth_details",
                form_checklist_visibility: true,
                form_checklist_placeholder: "Enter Std 10th Details",
                form_checklist_lable: "",
                form_checklist_typo: "CHECKBOX",
                form_checklist_sample: "Std 10th Details",
                form_checklist_typo_option_pl: ["Std 10th Details"],
                nested_form_checklist: [
                    {
                        form_checklist_name: "Month of Passing",
                        form_checklist_key: "month_of_passing",
                        form_checklist_visibility: true,
                        form_checklist_placeholder: "Enter Month of Passing",
                        form_checklist_lable: "Enter Month of Passing",
                        form_checklist_typo: "TEXT",
                        form_checklist_sample: "Month of Passing",
                        form_checklist_typo_option_pl: [],
                    },
                    {
                        form_checklist_name: "Year of Passing",
                        form_checklist_key: "year_of_passing",
                        form_checklist_visibility: true,
                        form_checklist_placeholder: "Enter Year of Passing",
                        form_checklist_lable: "Enter Year of Passing",
                        form_checklist_typo: "TEXT",
                        form_checklist_sample: "Year of Passing",
                        form_checklist_typo_option_pl: [],
                    },
                    {
                        form_checklist_name: "Percentage",
                        form_checklist_key: "percentage",
                        form_checklist_visibility: true,
                        form_checklist_placeholder: "Enter Percentage",
                        form_checklist_lable: "Enter Percentage",
                        form_checklist_typo: "NUMBER",
                        form_checklist_sample: "Percentage",
                        form_checklist_typo_option_pl: [],
                    },
                    {
                        form_checklist_name: "Name of Institute",
                        form_checklist_key: "name_of_institute",
                        form_checklist_visibility: true,
                        form_checklist_placeholder: "Enter Name of Institute",
                        form_checklist_lable: "Enter Name of Institute",
                        form_checklist_typo: "TEXT",
                        form_checklist_sample: "Name of Institute",
                        form_checklist_typo_option_pl: [],
                    }
                ]
            },
            {
                form_checklist_name: "HSC (10+2) / Diploma",
                form_checklist_key: "hsc_diploma",
                form_checklist_visibility: true,
                form_checklist_placeholder: "Enter HSC (10+2) / Diploma",
                form_checklist_lable: "",
                form_checklist_typo: "CHECKBOX",
                form_checklist_sample: "HSC (10+2) / Diploma",
                form_checklist_typo_option_pl: ["HSC (10+2) / Diploma"],
                nested_form_checklist: [
                    {
                        form_checklist_name: "Month",
                        form_checklist_key: "hsc_month",
                        form_checklist_visibility: true,
                        form_checklist_placeholder: "Enter Month",
                        form_checklist_lable: "Enter Month",
                        form_checklist_typo: "TEXT",
                        form_checklist_sample: "Month",
                        form_checklist_typo_option_pl: [],
                    },
                    {
                        form_checklist_name: "Year",
                        form_checklist_key: "hsc_year",
                        form_checklist_visibility: true,
                        form_checklist_placeholder: "Enter Year",
                        form_checklist_lable: "Enter Year",
                        form_checklist_typo: "TEXT",
                        form_checklist_sample: "Year",
                        form_checklist_typo_option_pl: [],
                    },
                    {
                        form_checklist_name: "Percentage",
                        form_checklist_key: "hsc_percentage",
                        form_checklist_visibility: true,
                        form_checklist_placeholder: "Enter Percentage",
                        form_checklist_lable: "Enter Percentage",
                        form_checklist_typo: "NUMBER",
                        form_checklist_sample: "Percentage",
                        form_checklist_typo_option_pl: [],
                    },
                    {
                        form_checklist_name: "Name of Institute",
                        form_checklist_key: "hsc_name_of_institute",
                        form_checklist_visibility: true,
                        form_checklist_placeholder: "Enter Name of Institute",
                        form_checklist_lable: "Enter Name of Institute",
                        form_checklist_typo: "TEXT",
                        form_checklist_sample: "Name of Institute",
                        form_checklist_typo_option_pl: [],
                    },
                    {
                        form_checklist_name: "Board",
                        form_checklist_key: "hsc_board",
                        form_checklist_visibility: true,
                        form_checklist_placeholder: "Enter Board",
                        form_checklist_lable: "Enter Board",
                        form_checklist_typo: "TEXT",
                        form_checklist_sample: "Board",
                        form_checklist_typo_option_pl: [],
                    },
                    {
                        form_checklist_name: "Candidate Type",
                        form_checklist_key: "hsc_candidate_type",
                        form_checklist_visibility: true,
                        form_checklist_placeholder: "Enter Candidate Type",
                        form_checklist_lable: "Enter Candidate Type",
                        form_checklist_typo: "TEXT",
                        form_checklist_sample: "Candidate Type",
                        form_checklist_typo_option_pl: [],
                    },
                    {
                        form_checklist_name: "Vocational Type",
                        form_checklist_key: "hsc_vocational_type",
                        form_checklist_visibility: true,
                        form_checklist_placeholder: "Enter Vocational Type",
                        form_checklist_lable: "Enter Vocational Type",
                        form_checklist_typo: "TEXT",
                        form_checklist_sample: "Vocational Type",
                        form_checklist_typo_option_pl: [],
                    },
                    {
                        form_checklist_name: "Physics Marks Obtained",
                        form_checklist_key: "hsc_physics_marks",
                        form_checklist_visibility: true,
                        form_checklist_placeholder: "Enter Physics Marks Obtained",
                        form_checklist_lable: "Enter Physics Marks Obtained",
                        form_checklist_typo: "NUMBER",
                        form_checklist_sample: "Physics Marks Obtained",
                        form_checklist_typo_option_pl: [],
                    },
                    {
                        form_checklist_name: "Chemistry Marks Obtained",
                        form_checklist_key: "hsc_chemistry_marks",
                        form_checklist_visibility: true,
                        form_checklist_placeholder: "Enter Chemistry Marks Obtained",
                        form_checklist_lable: "Enter Chemistry Marks Obtained",
                        form_checklist_typo: "NUMBER",
                        form_checklist_sample: "Chemistry Marks Obtained",
                        form_checklist_typo_option_pl: [],
                    },
                    {
                        form_checklist_name: "Mathematics Marks Obtained",
                        form_checklist_key: "hsc_mathematics_marks",
                        form_checklist_visibility: true,
                        form_checklist_placeholder: "Enter Mathematics Marks Obtained",
                        form_checklist_lable: "Enter Mathematics Marks Obtained",
                        form_checklist_typo: "NUMBER",
                        form_checklist_sample: "Mathematics Marks Obtained",
                        form_checklist_typo_option_pl: [],
                    },
                    {
                        form_checklist_name: "PCM Total",
                        form_checklist_key: "hsc_pcm_total",
                        form_checklist_visibility: true,
                        form_checklist_placeholder: "Enter PCM Total",
                        form_checklist_lable: "Enter PCM Total",
                        form_checklist_typo: "NUMBER",
                        form_checklist_sample: "PCM Total",
                        form_checklist_typo_option_pl: [],
                    },
                    {
                        form_checklist_name: "HSC Grand Total",
                        form_checklist_key: "hsc_grand_total",
                        form_checklist_visibility: true,
                        form_checklist_placeholder: "Enter HSC Grand Total",
                        form_checklist_lable: "Enter HSC Grand Total",
                        form_checklist_typo: "NUMBER",
                        form_checklist_sample: "HSC Grand Total",
                        form_checklist_typo_option_pl: [],
                    }
                ]
            },
            {
                form_checklist_name: "UG For Engineering",
                form_checklist_key: "ug_engineering",
                form_checklist_visibility: true,
                form_checklist_placeholder: "Enter UG For Engineering",
                form_checklist_lable: "",
                form_checklist_typo: "CHECKBOX",
                form_checklist_sample: "UG For Engineering",
                form_checklist_typo_option_pl: ["UG For Engineering"],
                nested_form_checklist: [
                    {
                        form_checklist_name: "Pre-final Sem",
                        form_checklist_key: "pre_final_sem",
                        form_checklist_visibility: true,
                        form_checklist_placeholder: "Enter Pre-final Sem",
                        form_checklist_lable: "",
                        form_checklist_typo: "CHECKBOX",
                        form_checklist_sample: "Pre-final Sem",
                        form_checklist_typo_option_pl: ["Pre-final Sem"],
                        nested_form_checklist_nested: [
                            {
                                form_checklist_name: "Marks / Credits Obtain",
                                form_checklist_key: "pre_marks_credit_obtain",
                                form_checklist_visibility: true,
                                form_checklist_placeholder: "Enter Marks / Credits Obtain",
                                form_checklist_lable: "Enter Marks / Credits Obtain",
                                form_checklist_typo: "NUMBER",
                                form_checklist_sample: "Marks / Credits Obtain",
                                form_checklist_typo_option_pl: [],
                            },
                            {
                                form_checklist_name: "Total Grade Points",
                                form_checklist_key: "pre_total_grade_points",
                                form_checklist_visibility: true,
                                form_checklist_placeholder: "Enter Total Grade Points",
                                form_checklist_lable: "Enter Total Grade Points",
                                form_checklist_typo: "NUMBER",
                                form_checklist_sample: "Total Grade Points",
                                form_checklist_typo_option_pl: [],
                            },
                        ]
                    },
                    {
                        form_checklist_name: "Final Sem / Year",
                        form_checklist_key: "final_sem",
                        form_checklist_visibility: true,
                        form_checklist_placeholder: "Enter Final Sem / Year",
                        form_checklist_lable: "",
                        form_checklist_typo: "CHECKBOX",
                        form_checklist_sample: "Final Sem / Year",
                        form_checklist_typo_option_pl: ["Final Sem / Year"],
                        nested_form_checklist_nested: [
                            {
                                form_checklist_name: "Marks / Credits Obtain",
                                form_checklist_key: "final_marks_credit_obtain",
                                form_checklist_visibility: true,
                                form_checklist_placeholder: "Enter Marks / Credits Obtain",
                                form_checklist_lable: "Enter Marks / Credits Obtain",
                                form_checklist_typo: "NUMBER",
                                form_checklist_sample: "Marks / Credits Obtain",
                                form_checklist_typo_option_pl: [],
                            },
                            {
                                form_checklist_name: "Total Grade Points",
                                form_checklist_key: "final_total_grade_points",
                                form_checklist_visibility: true,
                                form_checklist_placeholder: "Enter Total Grade Points",
                                form_checklist_lable: "Enter Total Grade Points",
                                form_checklist_typo: "NUMBER",
                                form_checklist_sample: "Total Grade Points",
                                form_checklist_typo_option_pl: [],
                            },
                            {
                                form_checklist_name: "CPI",
                                form_checklist_key: "final_cpi",
                                form_checklist_visibility: true,
                                form_checklist_placeholder: "Enter CPI",
                                form_checklist_lable: "Enter CPI",
                                form_checklist_typo: "NUMBER",
                                form_checklist_sample: "CPI",
                                form_checklist_typo_option_pl: [],
                            },
                        ]
                    }
                ]
            },
            {
                form_checklist_name: "Entrance Exam",
                form_checklist_key: "entrance_exam",
                form_checklist_visibility: true,
                form_checklist_placeholder: "Enter Entrance Exam",
                form_checklist_lable: "",
                form_checklist_typo: "CHECKBOX",
                form_checklist_sample: "Entrance Exam",
                form_checklist_typo_option_pl: ["Entrance Exam"],
                nested_form_checklist: [
                    {
                        form_checklist_name: "JEE Details",
                        form_checklist_key: "jee_details",
                        form_checklist_visibility: true,
                        form_checklist_placeholder: "Enter JEE Details",
                        form_checklist_lable: "",
                        form_checklist_typo: "CHECKBOX",
                        form_checklist_sample: "JEE Details",
                        form_checklist_typo_option_pl: ["JEE Details"],
                        nested_form_checklist_nested: [
                            {
                                form_checklist_name: "ROLL No.",
                                form_checklist_key: "jee_rollno",
                                form_checklist_visibility: true,
                                form_checklist_placeholder: "Enter ROLL No.",
                                form_checklist_lable: "Enter ROLL No.",
                                form_checklist_typo: "TEXT",
                                form_checklist_sample: "ROLL No.",
                                form_checklist_typo_option_pl: [],
                            },
                            {
                                form_checklist_name: "Physics Marks Obtained",
                                form_checklist_key: "jee_physics_marks",
                                form_checklist_visibility: true,
                                form_checklist_placeholder: "Enter Physics Marks Obtained",
                                form_checklist_lable: "Enter Physics Marks Obtained",
                                form_checklist_typo: "NUMBER",
                                form_checklist_sample: "Physics Marks Obtained",
                                form_checklist_typo_option_pl: [],
                            },
                            {
                                form_checklist_name: "Chemistry Marks Obtained",
                                form_checklist_key: "jee_chemistry_marks",
                                form_checklist_visibility: true,
                                form_checklist_placeholder: "Enter Chemistry Marks Obtained",
                                form_checklist_lable: "Enter Chemistry Marks Obtained",
                                form_checklist_typo: "NUMBER",
                                form_checklist_sample: "Chemistry Marks Obtained",
                                form_checklist_typo_option_pl: [],
                            },
                            {
                                form_checklist_name: "Mathematics Marks Obtained",
                                form_checklist_key: "jee_mathematics_marks",
                                form_checklist_visibility: true,
                                form_checklist_placeholder: "Enter Mathematics Marks Obtained",
                                form_checklist_lable: "Enter Mathematics Marks Obtained",
                                form_checklist_typo: "NUMBER",
                                form_checklist_sample: "Mathematics Marks Obtained",
                                form_checklist_typo_option_pl: [],
                            },
                            {
                                form_checklist_name: "JEE Total",
                                form_checklist_key: "jee_total",
                                form_checklist_visibility: true,
                                form_checklist_placeholder: "Enter JEE Total",
                                form_checklist_lable: "Enter JEE Total",
                                form_checklist_typo: "NUMBER",
                                form_checklist_sample: "JEE Total",
                                form_checklist_typo_option_pl: [],
                            },
                            {
                                form_checklist_name: "JEE Percentile",
                                form_checklist_key: "jee_percentile",
                                form_checklist_visibility: true,
                                form_checklist_placeholder: "Enter JEE Percentile",
                                form_checklist_lable: "Enter JEE Percentile",
                                form_checklist_typo: "NUMBER",
                                form_checklist_sample: "JEE Percentile",
                                form_checklist_typo_option_pl: [],
                            }
                        ]
                    },
                    {
                        form_checklist_name: "CET Details",
                        form_checklist_key: "cet_details",
                        form_checklist_visibility: true,
                        form_checklist_placeholder: "Enter CET Details",
                        form_checklist_lable: "",
                        form_checklist_typo: "CHECKBOX",
                        form_checklist_sample: "CET Details",
                        form_checklist_typo_option_pl: ["CET Details"],
                        nested_form_checklist_nested: [
                            {
                                form_checklist_name: "ROLL No.",
                                form_checklist_key: "cet_rollno",
                                form_checklist_visibility: true,
                                form_checklist_placeholder: "Enter ROLL No.",
                                form_checklist_lable: "Enter ROLL No.",
                                form_checklist_typo: "TEXT",
                                form_checklist_sample: "ROLL No.",
                                form_checklist_typo_option_pl: [],
                            },
                            {
                                form_checklist_name: "Physics Marks Obtained",
                                form_checklist_key: "cet_physics_marks",
                                form_checklist_visibility: true,
                                form_checklist_placeholder: "Enter Physics Marks Obtained",
                                form_checklist_lable: "Enter Physics Marks Obtained",
                                form_checklist_typo: "NUMBER",
                                form_checklist_sample: "Physics Marks Obtained",
                                form_checklist_typo_option_pl: [],
                            },
                            {
                                form_checklist_name: "Chemistry Marks Obtained",
                                form_checklist_key: "cet_chemistry_marks",
                                form_checklist_visibility: true,
                                form_checklist_placeholder: "Enter Chemistry Marks Obtained",
                                form_checklist_lable: "Enter Chemistry Marks Obtained",
                                form_checklist_typo: "NUMBER",
                                form_checklist_sample: "Chemistry Marks Obtained",
                                form_checklist_typo_option_pl: [],
                            },
                            {
                                form_checklist_name: "Mathematics Marks Obtained",
                                form_checklist_key: "cet_mathematics_marks",
                                form_checklist_visibility: true,
                                form_checklist_placeholder: "Enter Mathematics Marks Obtained",
                                form_checklist_lable: "Enter Mathematics Marks Obtained",
                                form_checklist_typo: "NUMBER",
                                form_checklist_sample: "Mathematics Marks Obtained",
                                form_checklist_typo_option_pl: [],
                            },
                            {
                                form_checklist_name: "Biology Marks Obtained",
                                form_checklist_key: "cet_biology_marks",
                                form_checklist_visibility: true,
                                form_checklist_placeholder: "Enter Biology Marks Obtained",
                                form_checklist_lable: "Enter Biology Marks Obtained",
                                form_checklist_typo: "NUMBER",
                                form_checklist_sample: "Biology Marks Obtained",
                                form_checklist_typo_option_pl: [],
                            },
                            {
                                form_checklist_name: "CET Total",
                                form_checklist_key: "cet_total",
                                form_checklist_visibility: true,
                                form_checklist_placeholder: "Enter CET Total",
                                form_checklist_lable: "Enter CET Total",
                                form_checklist_typo: "NUMBER",
                                form_checklist_sample: "CET Total",
                                form_checklist_typo_option_pl: [],
                            },
                            {
                                form_checklist_name: "CET Percentile",
                                form_checklist_key: "cet_percentile",
                                form_checklist_visibility: true,
                                form_checklist_placeholder: "Enter CET Percentile",
                                form_checklist_lable: "Enter CET Percentile",
                                form_checklist_typo: "NUMBER",
                                form_checklist_sample: "CET Percentile",
                                form_checklist_typo_option_pl: [],
                            }
                        ]
                    },
                    {
                        form_checklist_name: "AIEEE Details",
                        form_checklist_key: "aieee_details",
                        form_checklist_visibility: true,
                        form_checklist_placeholder: "Enter AIEEE Details",
                        form_checklist_lable: "",
                        form_checklist_typo: "CHECKBOX",
                        form_checklist_sample: "AIEEE Details",
                        form_checklist_typo_option_pl: ["AIEEE Details"],
                        nested_form_checklist_nested: [
                            {
                                form_checklist_name: "ROLL No.",
                                form_checklist_key: "aieee_rollno",
                                form_checklist_visibility: true,
                                form_checklist_placeholder: "Enter ROLL No.",
                                form_checklist_lable: "Enter ROLL No.",
                                form_checklist_typo: "TEXT",
                                form_checklist_sample: "ROLL No.",
                                form_checklist_typo_option_pl: [],
                            },
                            {
                                form_checklist_name: "Physics Marks Obtained",
                                form_checklist_key: "aieee_physics_marks",
                                form_checklist_visibility: true,
                                form_checklist_placeholder: "Enter Physics Marks Obtained",
                                form_checklist_lable: "Enter Physics Marks Obtained",
                                form_checklist_typo: "NUMBER",
                                form_checklist_sample: "Physics Marks Obtained",
                                form_checklist_typo_option_pl: [],
                            },
                            {
                                form_checklist_name: "Chemistry Marks Obtained",
                                form_checklist_key: "aieee_chemistry_marks",
                                form_checklist_visibility: true,
                                form_checklist_placeholder: "Enter Chemistry Marks Obtained",
                                form_checklist_lable: "Enter Chemistry Marks Obtained",
                                form_checklist_typo: "NUMBER",
                                form_checklist_sample: "Chemistry Marks Obtained",
                                form_checklist_typo_option_pl: [],
                            },
                            {
                                form_checklist_name: "Mathematics Marks Obtained",
                                form_checklist_key: "aieee_mathematics_marks",
                                form_checklist_visibility: true,
                                form_checklist_placeholder: "Enter Mathematics Marks Obtained",
                                form_checklist_lable: "Enter Mathematics Marks Obtained",
                                form_checklist_typo: "NUMBER",
                                form_checklist_sample: "Mathematics Marks Obtained",
                                form_checklist_typo_option_pl: [],
                            },
                            {
                                form_checklist_name: "Biology Marks Obtained",
                                form_checklist_key: "aieee_biology_marks",
                                form_checklist_visibility: true,
                                form_checklist_placeholder: "Enter Biology Marks Obtained",
                                form_checklist_lable: "Enter Biology Marks Obtained",
                                form_checklist_typo: "NUMBER",
                                form_checklist_sample: "Biology Marks Obtained",
                                form_checklist_typo_option_pl: [],
                            },
                            {
                                form_checklist_name: "AIEEE Total",
                                form_checklist_key: "aieee_total",
                                form_checklist_visibility: true,
                                form_checklist_placeholder: "Enter AIEEE Total",
                                form_checklist_lable: "Enter AIEEE Total",
                                form_checklist_typo: "NUMBER",
                                form_checklist_sample: "AIEEE Total",
                                form_checklist_typo_option_pl: [],
                            },
                            {
                                form_checklist_name: "AIEEE Percentile",
                                form_checklist_key: "aieee_percentile",
                                form_checklist_visibility: true,
                                form_checklist_placeholder: "Enter AIEEE Percentile",
                                form_checklist_lable: "Enter AIEEE Percentile",
                                form_checklist_typo: "NUMBER",
                                form_checklist_sample: "AIEEE Percentile",
                                form_checklist_typo_option_pl: [],
                            }
                        ]
                    }
                ]
            },
            {
                form_checklist_name: "F.Y.J.C",
                form_checklist_key: "fyjc",
                form_checklist_visibility: true,
                form_checklist_placeholder: "Enter F.Y.J.C",
                form_checklist_lable: "",
                form_checklist_typo: "CHECKBOX",
                form_checklist_sample: "F.Y.J.C",
                form_checklist_typo_option_pl: ["F.Y.J.C"],
                form_checklist_key_status: "DYNAMIC",
                nested_form_checklist: [
                    {
                        form_checklist_name: "Month of Passing",
                        form_checklist_key: "fyjc_month_of_passing",
                        form_checklist_visibility: true,
                        form_checklist_placeholder: "Enter Month of Passing",
                        form_checklist_lable: "Enter Month of Passing",
                        form_checklist_typo: "TEXT",
                        form_checklist_sample: "Month of Passing",
                        form_checklist_typo_option_pl: [],
                        form_checklist_key_status: "DYNAMIC"
                    },
                    {
                        form_checklist_name: "Year of Passing",
                        form_checklist_key: "fyjc_year_of_passing",
                        form_checklist_visibility: true,
                        form_checklist_placeholder: "Enter Year of Passing",
                        form_checklist_lable: "Enter Year of Passing",
                        form_checklist_typo: "TEXT",
                        form_checklist_sample: "Year of Passing",
                        form_checklist_typo_option_pl: [],
                        form_checklist_key_status: "DYNAMIC"
                    },
                    {
                        form_checklist_name: "Percentage",
                        form_checklist_key: "fyjc_percentage",
                        form_checklist_visibility: true,
                        form_checklist_placeholder: "Enter Percentage",
                        form_checklist_lable: "Enter Percentage",
                        form_checklist_typo: "NUMBER",
                        form_checklist_sample: "Percentage",
                        form_checklist_typo_option_pl: [],
                        form_checklist_key_status: "DYNAMIC"
                    },
                    {
                        form_checklist_name: "Name of Institute",
                        form_checklist_key: "fyjc_name_of_institute",
                        form_checklist_visibility: true,
                        form_checklist_placeholder: "Enter Name of Institute",
                        form_checklist_lable: "Enter Name of Institute",
                        form_checklist_typo: "TEXT",
                        form_checklist_sample: "Name of Institute",
                        form_checklist_typo_option_pl: [],
                        form_checklist_key_status: "DYNAMIC"
                    }
                ]
            },
            {
                form_checklist_name: "F.Y. Sem-I",
                form_checklist_key: "fy_sem_I",
                form_checklist_visibility: true,
                form_checklist_placeholder: "Enter F.Y. Sem-I",
                form_checklist_lable: "",
                form_checklist_typo: "CHECKBOX",
                form_checklist_sample: "F.Y. Sem-I",
                form_checklist_typo_option_pl: ["F.Y. Sem-I"],
                form_checklist_key_status: "DYNAMIC",
                nested_form_checklist: [
                    {
                        form_checklist_name: "Month of Passing",
                        form_checklist_key: "fy_sem_I_month_of_passing",
                        form_checklist_visibility: true,
                        form_checklist_placeholder: "Enter Month of Passing",
                        form_checklist_lable: "Enter Month of Passing",
                        form_checklist_typo: "TEXT",
                        form_checklist_sample: "Month of Passing",
                        form_checklist_typo_option_pl: [],
                        form_checklist_key_status: "DYNAMIC"
                    },
                    {
                        form_checklist_name: "Year of Passing",
                        form_checklist_key: "fy_sem_I_year_of_passing",
                        form_checklist_visibility: true,
                        form_checklist_placeholder: "Enter Year of Passing",
                        form_checklist_lable: "Enter Year of Passing",
                        form_checklist_typo: "TEXT",
                        form_checklist_sample: "Year of Passing",
                        form_checklist_typo_option_pl: [],
                        form_checklist_key_status: "DYNAMIC"
                    },
                    {
                        form_checklist_name: "Percentage",
                        form_checklist_key: "fy_sem_I_percentage",
                        form_checklist_visibility: true,
                        form_checklist_placeholder: "Enter Percentage",
                        form_checklist_lable: "Enter Percentage",
                        form_checklist_typo: "NUMBER",
                        form_checklist_sample: "Percentage",
                        form_checklist_typo_option_pl: [],
                        form_checklist_key_status: "DYNAMIC"
                    },
                    {
                        form_checklist_name: "Name of Institute",
                        form_checklist_key: "fy_sem_I_name_of_institute",
                        form_checklist_visibility: true,
                        form_checklist_placeholder: "Enter Name of Institute",
                        form_checklist_lable: "Enter Name of Institute",
                        form_checklist_typo: "TEXT",
                        form_checklist_sample: "Name of Institute",
                        form_checklist_typo_option_pl: [],
                        form_checklist_key_status: "DYNAMIC"
                    }
                ]
            },
            {
                form_checklist_name: "F.Y. Sem-II",
                form_checklist_key: "fy_sem_II",
                form_checklist_visibility: true,
                form_checklist_placeholder: "Enter F.Y. Sem-II",
                form_checklist_lable: "",
                form_checklist_typo: "CHECKBOX",
                form_checklist_sample: "F.Y. Sem-II",
                form_checklist_typo_option_pl: ["F.Y. Sem-II"],
                form_checklist_key_status: "DYNAMIC",
                nested_form_checklist: [
                    {
                        form_checklist_name: "Month of Passing",
                        form_checklist_key: "fy_sem_II_month_of_passing",
                        form_checklist_visibility: true,
                        form_checklist_placeholder: "Enter Month of Passing",
                        form_checklist_lable: "Enter Month of Passing",
                        form_checklist_typo: "TEXT",
                        form_checklist_sample: "Month of Passing",
                        form_checklist_typo_option_pl: [],
                        form_checklist_key_status: "DYNAMIC"
                    },
                    {
                        form_checklist_name: "Year of Passing",
                        form_checklist_key: "fy_sem_II_year_of_passing",
                        form_checklist_visibility: true,
                        form_checklist_placeholder: "Enter Year of Passing",
                        form_checklist_lable: "Enter Year of Passing",
                        form_checklist_typo: "TEXT",
                        form_checklist_sample: "Year of Passing",
                        form_checklist_typo_option_pl: [],
                        form_checklist_key_status: "DYNAMIC"
                    },
                    {
                        form_checklist_name: "Percentage",
                        form_checklist_key: "fy_sem_II_percentage",
                        form_checklist_visibility: true,
                        form_checklist_placeholder: "Enter Percentage",
                        form_checklist_lable: "Enter Percentage",
                        form_checklist_typo: "NUMBER",
                        form_checklist_sample: "Percentage",
                        form_checklist_typo_option_pl: [],
                        form_checklist_key_status: "DYNAMIC"
                    },
                    {
                        form_checklist_name: "Name of Institute",
                        form_checklist_key: "fy_sem_II_name_of_institute",
                        form_checklist_visibility: true,
                        form_checklist_placeholder: "Enter Name of Institute",
                        form_checklist_lable: "Enter Name of Institute",
                        form_checklist_typo: "TEXT",
                        form_checklist_sample: "Name of Institute",
                        form_checklist_typo_option_pl: [],
                        form_checklist_key_status: "DYNAMIC"
                    }
                ]
            },
            {
                form_checklist_name: "S.Y. Sem-III",
                form_checklist_key: "sy_sem_III",
                form_checklist_visibility: true,
                form_checklist_placeholder: "Enter S.Y. Sem-III",
                form_checklist_lable: "",
                form_checklist_typo: "CHECKBOX",
                form_checklist_sample: "S.Y. Sem-III",
                form_checklist_typo_option_pl: ["S.Y. Sem-III"],
                form_checklist_key_status: "DYNAMIC",
                nested_form_checklist: [
                    {
                        form_checklist_name: "Month of Passing",
                        form_checklist_key: "sy_sem_III_month_of_passing",
                        form_checklist_visibility: true,
                        form_checklist_placeholder: "Enter Month of Passing",
                        form_checklist_lable: "Enter Month of Passing",
                        form_checklist_typo: "TEXT",
                        form_checklist_sample: "Month of Passing",
                        form_checklist_typo_option_pl: [],
                        form_checklist_key_status: "DYNAMIC"
                    },
                    {
                        form_checklist_name: "Year of Passing",
                        form_checklist_key: "sy_sem_III_year_of_passing",
                        form_checklist_visibility: true,
                        form_checklist_placeholder: "Enter Year of Passing",
                        form_checklist_lable: "Enter Year of Passing",
                        form_checklist_typo: "TEXT",
                        form_checklist_sample: "Year of Passing",
                        form_checklist_typo_option_pl: [],
                        form_checklist_key_status: "DYNAMIC"
                    },
                    {
                        form_checklist_name: "Percentage",
                        form_checklist_key: "sy_sem_III_percentage",
                        form_checklist_visibility: true,
                        form_checklist_placeholder: "Enter Percentage",
                        form_checklist_lable: "Enter Percentage",
                        form_checklist_typo: "NUMBER",
                        form_checklist_sample: "Percentage",
                        form_checklist_typo_option_pl: [],
                        form_checklist_key_status: "DYNAMIC"
                    },
                    {
                        form_checklist_name: "Name of Institute",
                        form_checklist_key: "sy_sem_III_name_of_institute",
                        form_checklist_visibility: true,
                        form_checklist_placeholder: "Enter Name of Institute",
                        form_checklist_lable: "Enter Name of Institute",
                        form_checklist_typo: "TEXT",
                        form_checklist_sample: "Name of Institute",
                        form_checklist_typo_option_pl: [],
                        form_checklist_key_status: "DYNAMIC"
                    }
                ]
            },
            {
                form_checklist_name: "S.Y. Sem-IV",
                form_checklist_key: "sy_sem_IV",
                form_checklist_visibility: true,
                form_checklist_placeholder: "Enter S.Y. Sem-IV",
                form_checklist_lable: "",
                form_checklist_typo: "CHECKBOX",
                form_checklist_sample: "S.Y. Sem-IV",
                form_checklist_typo_option_pl: ["S.Y. Sem-IV"],
                form_checklist_key_status: "DYNAMIC",
                nested_form_checklist: [
                    {
                        form_checklist_name: "Month of Passing",
                        form_checklist_key: "sy_sem_IV_month_of_passing",
                        form_checklist_visibility: true,
                        form_checklist_placeholder: "Enter Month of Passing",
                        form_checklist_lable: "Enter Month of Passing",
                        form_checklist_typo: "TEXT",
                        form_checklist_sample: "Month of Passing",
                        form_checklist_typo_option_pl: [],
                        form_checklist_key_status: "DYNAMIC"
                    },
                    {
                        form_checklist_name: "Year of Passing",
                        form_checklist_key: "sy_sem_IV_year_of_passing",
                        form_checklist_visibility: true,
                        form_checklist_placeholder: "Enter Year of Passing",
                        form_checklist_lable: "Enter Year of Passing",
                        form_checklist_typo: "TEXT",
                        form_checklist_sample: "Year of Passing",
                        form_checklist_typo_option_pl: [],
                        form_checklist_key_status: "DYNAMIC"
                    },
                    {
                        form_checklist_name: "Percentage",
                        form_checklist_key: "sy_sem_IV_percentage",
                        form_checklist_visibility: true,
                        form_checklist_placeholder: "Enter Percentage",
                        form_checklist_lable: "Enter Percentage",
                        form_checklist_typo: "NUMBER",
                        form_checklist_sample: "Percentage",
                        form_checklist_typo_option_pl: [],
                        form_checklist_key_status: "DYNAMIC"
                    },
                    {
                        form_checklist_name: "Name of Institute",
                        form_checklist_key: "sy_sem_IV_name_of_institute",
                        form_checklist_visibility: true,
                        form_checklist_placeholder: "Enter Name of Institute",
                        form_checklist_lable: "Enter Name of Institute",
                        form_checklist_typo: "TEXT",
                        form_checklist_sample: "Name of Institute",
                        form_checklist_typo_option_pl: [],
                        form_checklist_key_status: "DYNAMIC"
                    }
                ]
            },
            {
                form_checklist_name: "T.Y. Sem-V",
                form_checklist_key: "ty_sem_V",
                form_checklist_visibility: true,
                form_checklist_placeholder: "Enter T.Y. Sem-V",
                form_checklist_lable: "",
                form_checklist_typo: "CHECKBOX",
                form_checklist_sample: "T.Y. Sem-V",
                form_checklist_typo_option_pl: ["T.Y. Sem-V"],
                form_checklist_key_status: "DYNAMIC",
                nested_form_checklist: [
                    {
                        form_checklist_name: "Month of Passing",
                        form_checklist_key: "ty_sem_V_month_of_passing",
                        form_checklist_visibility: true,
                        form_checklist_placeholder: "Enter Month of Passing",
                        form_checklist_lable: "Enter Month of Passing",
                        form_checklist_typo: "TEXT",
                        form_checklist_sample: "Month of Passing",
                        form_checklist_typo_option_pl: [],
                        form_checklist_key_status: "DYNAMIC"
                    },
                    {
                        form_checklist_name: "Year of Passing",
                        form_checklist_key: "ty_sem_V_year_of_passing",
                        form_checklist_visibility: true,
                        form_checklist_placeholder: "Enter Year of Passing",
                        form_checklist_lable: "Enter Year of Passing",
                        form_checklist_typo: "TEXT",
                        form_checklist_sample: "Year of Passing",
                        form_checklist_typo_option_pl: [],
                        form_checklist_key_status: "DYNAMIC"
                    },
                    {
                        form_checklist_name: "Percentage",
                        form_checklist_key: "ty_sem_V_percentage",
                        form_checklist_visibility: true,
                        form_checklist_placeholder: "Enter Percentage",
                        form_checklist_lable: "Enter Percentage",
                        form_checklist_typo: "NUMBER",
                        form_checklist_sample: "Percentage",
                        form_checklist_typo_option_pl: [],
                        form_checklist_key_status: "DYNAMIC"
                    },
                    {
                        form_checklist_name: "Name of Institute",
                        form_checklist_key: "ty_sem_V_name_of_institute",
                        form_checklist_visibility: true,
                        form_checklist_placeholder: "Enter Name of Institute",
                        form_checklist_lable: "Enter Name of Institute",
                        form_checklist_typo: "TEXT",
                        form_checklist_sample: "Name of Institute",
                        form_checklist_typo_option_pl: [],
                        form_checklist_key_status: "DYNAMIC"
                    }
                ]
            },
            {
                form_checklist_name: "T.Y. Sem-VI",
                form_checklist_key: "ty_sem_VI",
                form_checklist_visibility: true,
                form_checklist_placeholder: "Enter T.Y. Sem-VI",
                form_checklist_lable: "",
                form_checklist_typo: "CHECKBOX",
                form_checklist_sample: "T.Y. Sem-VI",
                form_checklist_typo_option_pl: ["T.Y. Sem-VI"],
                form_checklist_key_status: "DYNAMIC",
                nested_form_checklist: [
                    {
                        form_checklist_name: "Month of Passing",
                        form_checklist_key: "ty_sem_VI_month_of_passing",
                        form_checklist_visibility: true,
                        form_checklist_placeholder: "Enter Month of Passing",
                        form_checklist_lable: "Enter Month of Passing",
                        form_checklist_typo: "TEXT",
                        form_checklist_sample: "Month of Passing",
                        form_checklist_typo_option_pl: [],
                        form_checklist_key_status: "DYNAMIC"
                    },
                    {
                        form_checklist_name: "Year of Passing",
                        form_checklist_key: "ty_sem_VI_year_of_passing",
                        form_checklist_visibility: true,
                        form_checklist_placeholder: "Enter Year of Passing",
                        form_checklist_lable: "Enter Year of Passing",
                        form_checklist_typo: "TEXT",
                        form_checklist_sample: "Year of Passing",
                        form_checklist_typo_option_pl: [],
                        form_checklist_key_status: "DYNAMIC"
                    },
                    {
                        form_checklist_name: "Percentage",
                        form_checklist_key: "ty_sem_VI_percentage",
                        form_checklist_visibility: true,
                        form_checklist_placeholder: "Enter Percentage",
                        form_checklist_lable: "Enter Percentage",
                        form_checklist_typo: "NUMBER",
                        form_checklist_sample: "Percentage",
                        form_checklist_typo_option_pl: [],
                        form_checklist_key_status: "DYNAMIC"
                    },
                    {
                        form_checklist_name: "Name of Institute",
                        form_checklist_key: "ty_sem_VI_name_of_institute",
                        form_checklist_visibility: true,
                        form_checklist_placeholder: "Enter Name of Institute",
                        form_checklist_lable: "Enter Name of Institute",
                        form_checklist_typo: "TEXT",
                        form_checklist_sample: "Name of Institute",
                        form_checklist_typo_option_pl: [],
                        form_checklist_key_status: "DYNAMIC"
                    }
                ]
            },
            {
                form_checklist_name: "M.Sc/M.Com",
                form_checklist_key: "msc_mcom",
                form_checklist_visibility: true,
                form_checklist_placeholder: "Enter M.Sc/M.Com",
                form_checklist_lable: "",
                form_checklist_typo: "CHECKBOX",
                form_checklist_sample: "M.Sc/M.Com",
                form_checklist_typo_option_pl: ["M.Sc/M.Com"],
                form_checklist_key_status: "DYNAMIC",
                nested_form_checklist: [
                    {
                        form_checklist_name: "Month of Passing",
                        form_checklist_key: "msc_mcom_month_of_passing",
                        form_checklist_visibility: true,
                        form_checklist_placeholder: "Enter Month of Passing",
                        form_checklist_lable: "Enter Month of Passing",
                        form_checklist_typo: "TEXT",
                        form_checklist_sample: "Month of Passing",
                        form_checklist_typo_option_pl: [],
                        form_checklist_key_status: "DYNAMIC"
                    },
                    {
                        form_checklist_name: "Year of Passing",
                        form_checklist_key: "msc_mcom_year_of_passing",
                        form_checklist_visibility: true,
                        form_checklist_placeholder: "Enter Year of Passing",
                        form_checklist_lable: "Enter Year of Passing",
                        form_checklist_typo: "TEXT",
                        form_checklist_sample: "Year of Passing",
                        form_checklist_typo_option_pl: [],
                        form_checklist_key_status: "DYNAMIC"
                    },
                    {
                        form_checklist_name: "Percentage",
                        form_checklist_key: "msc_mcom_percentage",
                        form_checklist_visibility: true,
                        form_checklist_placeholder: "Enter Percentage",
                        form_checklist_lable: "Enter Percentage",
                        form_checklist_typo: "NUMBER",
                        form_checklist_sample: "Percentage",
                        form_checklist_typo_option_pl: [],
                        form_checklist_key_status: "DYNAMIC"
                    },
                    {
                        form_checklist_name: "Name of Institute",
                        form_checklist_key: "msc_mcom_name_of_institute",
                        form_checklist_visibility: true,
                        form_checklist_placeholder: "Enter Name of Institute",
                        form_checklist_lable: "Enter Name of Institute",
                        form_checklist_typo: "TEXT",
                        form_checklist_sample: "Name of Institute",
                        form_checklist_typo_option_pl: [],
                        form_checklist_key_status: "DYNAMIC"
                    }
                ]
            },
        ]
    }
]