module.exports.form_params = [
    {
        section_name: "",
        section_visibilty: true,
        section_key: "",
        form_checklist: [
            {
                form_checklist_name: "Profile Photo",
                form_checklist_key: "studentProfilePhoto",
                form_checklist_visibility: true,
                form_checklist_placeholder: "Upload Profile Photo",
                form_checklist_lable: "Upload Profile Photo",
                form_checklist_typo: "CROPIMAGE",
                form_checklist_required: true
            }, 
            {
                form_checklist_name: "Passport Photo for ID Card",
                form_checklist_key: "studentIdProfilePhoto",
                form_checklist_visibility: true,
                form_checklist_placeholder: "Upload Passport Photo for ID Card",
                form_checklist_lable: "Upload Passport Photo for ID Card",
                form_checklist_typo: "CROPIMAGE",
            },
        ]
    },
    {
        section_name: "Basic Details",
        section_visibilty: true,
        section_key: "basic_details",
        form_checklist: [
            {
                form_checklist_name: "First Name",
                form_checklist_key: "studentFirstName",
                form_checklist_visibility: true,
                form_checklist_placeholder: "Enter Your First Name",
                form_checklist_lable: "Student First Name",
                form_checklist_typo: "TEXT",
                form_checklist_required: true,
                width: "32%"
            },
            {
                form_checklist_name: "Father Name",
                form_checklist_key: "studentFatherName",
                form_checklist_visibility: true,
                form_checklist_placeholder: "Enter Your Father Name",
                form_checklist_lable: "Student Father's Name",
                form_checklist_typo: "TEXT",
                form_checklist_required: true,
                width: "32%"
            },
            {
                form_checklist_name: "Surname",
                form_checklist_key: "studentLastName",
                form_checklist_visibility: true,
                form_checklist_placeholder: "Enter Your Surname",
                form_checklist_lable: "Student Surname",
                form_checklist_typo: "TEXT",
                form_checklist_required: true,
                width: "32%"
            },
            {
                form_checklist_name: "Date of Birth",
                form_checklist_key: "studentDOB",
                form_checklist_visibility: true,
                form_checklist_placeholder: "Date of Birth",
                form_checklist_lable: "DOB",
                form_checklist_typo: "CALENDAR",
                form_checklist_required: true
            },
            {
                form_checklist_name: "Gender",
                form_checklist_key: "studentGender",
                form_checklist_visibility: true,
                form_checklist_placeholder: "Select Gender",
                form_checklist_lable: "Select Gender / Sex",
                form_checklist_typo: "SELECT",
                form_checklist_required: true,
                form_checklist_typo_option_pl: ["Male", "Female", "Other"]
            },
            {
                form_checklist_name: "Mother's Name",
                form_checklist_key: "studentMotherName",
                form_checklist_visibility: true,
                form_checklist_placeholder: "Enter Mother's Name",
                form_checklist_lable: "Mother's Name",
                form_checklist_typo: "TEXT",
                form_checklist_required: true
            },
            {
                form_checklist_name: "Name as per marksheet",
                form_checklist_key: "studentNameAsMarksheet",
                form_checklist_visibility: true,
                form_checklist_placeholder: "Enter Name as per marksheet",
                form_checklist_lable: "Name as per marksheet",
                form_checklist_typo: "TEXT",
            },
            {
                form_checklist_name: "Name as per LC / TC",
                form_checklist_key: "studentNameAsCertificate",
                form_checklist_visibility: true,
                form_checklist_placeholder: "Enter Name as per LC / TC",
                form_checklist_lable: "Name as per LC / TC",
                form_checklist_typo: "TEXT",
            },
        ]
    },
    {
        section_name: "Other Details",
        section_visibilty: true,
        section_key: "other_details",
        form_checklist: [
            {
                form_checklist_name: "Place of Birth",
                form_checklist_key: "studentBirthPlace",
                form_checklist_visibility: true,
                form_checklist_placeholder: "Enter Your Place of Birth",
                form_checklist_lable: "Place of Birth",
                form_checklist_typo: "TEXT",
            },
            {
                form_checklist_name: "Religion",
                form_checklist_key: "studentReligion",
                form_checklist_visibility: true,
                form_checklist_placeholder: "Select Religion",
                form_checklist_lable: "Select Religion",
                form_checklist_typo: "SELECT",
                form_checklist_typo_option_pl: [
                    "Hindu",
                    "Muslim",
                    "Sikh",
                    "Christian",
                    "Parsi",
                    "Jews",
                    "Indigenous Faith",
                    "Buddhism",
                    "Jainism",
                  ]
            },
            {
                form_checklist_name: "Caste",
                form_checklist_key: "studentCast",
                form_checklist_visibility: true,
                form_checklist_placeholder: "Select Caste",
                form_checklist_lable: "Select Caste",
                form_checklist_typo: "TEXT",
            },
            {
                form_checklist_name: "Caste Category",
                form_checklist_key: "studentCastCategory",
                form_checklist_visibility: true,
                form_checklist_placeholder: "Select Caste Category",
                form_checklist_lable: "Select Caste Category",
                form_checklist_typo: "SELECT",
                form_checklist_typo_option_pl: [
                    "General",
                    "OBC",
                    "SC",
                    "ST",
                    "NT-A",
                    "NT-B",
                    "NT-C",
                    "NT-D",
                    "VJ",
                  ]
            },
            {
                form_checklist_name: "Nationality",
                form_checklist_key: "studentNationality",
                form_checklist_visibility: true,
                form_checklist_placeholder: "Select Nationality",
                form_checklist_lable: "Nationality",
                form_checklist_typo: "SELECT",
                form_checklist_typo_option_pl: ["Indian", "Non-Indian"]
            },
            {
                form_checklist_name: "Ration Card Color",
                form_checklist_key: "studentFatherRationCardColor",
                form_checklist_visibility: true,
                form_checklist_placeholder: "Select Ration Card Color",
                form_checklist_lable: "Ration Card Color",
                form_checklist_typo: "SELECT",
                form_checklist_typo_option_pl: ["White", "Yellow", "Orange", "Don't have ration Card"]
            },
            {
                form_checklist_name: "Blood Group",
                form_checklist_key: "student_blood_group",
                form_checklist_visibility: true,
                form_checklist_placeholder: "Select Blood Group",
                form_checklist_lable: "Blood Group",
                form_checklist_typo: "SELECT",
                form_checklist_typo_option_pl: ["A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-"]
            },
            {
                form_checklist_name: "Aadhar No.",
                form_checklist_key: "studentAadharNumber",
                form_checklist_visibility: true,
                form_checklist_placeholder: "Enter Aadhar No.",
                form_checklist_lable: "Aadhar No.",
                form_checklist_typo: "TEXT",
            },
        ]
    },
    {
        section_name: "Contact Details",
        section_visibilty: true,
        section_key: "contactDetails",
        form_checklist: [
            {
                form_checklist_name: "Student Contact No.",
                form_checklist_key: "studentPhoneNumber",
                form_checklist_visibility: true,
                form_checklist_placeholder: "Enter Student Contact No.",
                form_checklist_lable: "Student Contact No.",
                form_checklist_typo: "TEXT",
            },
            {
                form_checklist_name: "Student Email ID",
                form_checklist_key: "studentEmail",
                form_checklist_visibility: true,
                form_checklist_placeholder: "Enter Student Email ID",
                form_checklist_lable: "Student Email ID",
                form_checklist_typo: "TEXT",
            },
            {
                form_checklist_name: "Parents / Guardian Contact No.",
                form_checklist_key: "studentParentsPhoneNumber",
                form_checklist_visibility: true,
                form_checklist_placeholder: "Enter Parents / Guardian Contact No.",
                form_checklist_lable: "Parents / Guardian Contact No.",
                form_checklist_typo: "TEXT",
            },
            {
                form_checklist_name: "Student Current Address",
                form_checklist_key: "studentCurrentAddress",
                form_checklist_visibility: true,
                form_checklist_placeholder: "Enter Student Current Address",
                form_checklist_lable: "Student Current Address",
                form_checklist_typo: "TEXTAREA",
                width: "100%"
            },
            {
                form_checklist_name: "Student Current Pincode",
                form_checklist_key: "studentCurrentPincode",
                form_checklist_visibility: true,
                form_checklist_placeholder: "Enter Student Current Pincode",
                form_checklist_lable: "Student Current Pincode",
                form_checklist_typo: "TEXT",
                width: "32%"
            },
            {
                form_checklist_name: "Student Current State",
                form_checklist_key: "studentCurrentState",
                form_checklist_visibility: true,
                form_checklist_placeholder: "Enter Student Current State",
                form_checklist_lable: "Student Current State",
                form_checklist_typo: "TEXT",
                width: "32%"
            },
            {
                form_checklist_name: "Student Current District",
                form_checklist_key: "studentCurrentDistrict",
                form_checklist_visibility: true,
                form_checklist_placeholder: "Enter Student Current District",
                form_checklist_lable: "Student Current District",
                form_checklist_typo: "TEXT",
                width: "32%"
            },
            {
                form_checklist_name: "Student Permanent Address",
                form_checklist_key: "studentAddress",
                form_checklist_visibility: true,
                form_checklist_placeholder: "Enter Student Permanent Address",
                form_checklist_lable: "Student Permanent Address",
                form_checklist_typo: "TEXTAREA",
                width: "100%"
            },
            {
                form_checklist_name: "Student Permanent Pincode",
                form_checklist_key: "studentPincode",
                form_checklist_visibility: true,
                form_checklist_placeholder: "Enter Student Permanent Pincode",
                form_checklist_lable: "Student Permanent Pincode",
                form_checklist_typo: "TEXT",
                width: "32%"
            },
            {
                form_checklist_name: "Student Permanent State",
                form_checklist_key: "studentState",
                form_checklist_visibility: true,
                form_checklist_placeholder: "Enter Student Permanent State",
                form_checklist_lable: "Student Permanent State",
                form_checklist_typo: "TEXT",
                width: "32%"
            },
            {
                form_checklist_name: "Student Permanent District",
                form_checklist_key: "studentDistrict",
                form_checklist_visibility: true,
                form_checklist_placeholder: "Enter Student Permanent District",
                form_checklist_lable: "Student Permanent District",
                form_checklist_typo: "TEXT",
                width: "32%"
            },
        ]
    },
    {
        section_name: "Parent / Guardian Details",
        section_visibilty: true,
        section_key: "parentDetails",
        form_checklist: [
            {
                form_checklist_name: "Parent's Name",
                form_checklist_key: "studentParentsName",
                form_checklist_visibility: true,
                form_checklist_placeholder: "Enter Parent's Name",
                form_checklist_lable: "Parent's Name",
                form_checklist_typo: "TEXT",
            },
            {
                form_checklist_name: "Parent's Contact No.",
                form_checklist_key: "studentParentsPhoneNumber",
                form_checklist_visibility: true,
                form_checklist_placeholder: "Enter Parent's Contact No.",
                form_checklist_lable: "Parent's Contact No.",
                form_checklist_typo: "TEXT",
            },
            {
                form_checklist_name: "Parent's Email ID",
                form_checklist_key: "studentParentsEmail",
                form_checklist_visibility: true,
                form_checklist_placeholder: "Enter Parent's Email ID",
                form_checklist_lable: "Parent's Email ID",
                form_checklist_typo: "TEXT",
            },
            {
                form_checklist_name: "Parent's Occupation",
                form_checklist_key: "studentParentsOccupation",
                form_checklist_visibility: true,
                form_checklist_placeholder: "Enter Parent's Occupation",
                form_checklist_lable: "Parent's Occupation",
                form_checklist_typo: "TEXT",
            },
            {
                form_checklist_name: "Parent's Office Address",
                form_checklist_key: "studentParentsAddress",
                form_checklist_visibility: true,
                form_checklist_placeholder: "Enter Parent's Office Address",
                form_checklist_lable: "Parent's Office Address",
                form_checklist_typo: "TEXT",
            },
            {
                form_checklist_name: "Annual Income",
                form_checklist_key: "studentParentsAnnualIncom",
                form_checklist_visibility: true,
                form_checklist_placeholder: "Select Annual Income",
                form_checklist_lable: "Select Annual Income",
                form_checklist_typo: "SELECT",
                form_checklist_typo_option_pl: [
                    "Less than 1 Lac",
                    "Between 1 Lac to 2.5 lacs",
                    "Between 2.5 lacs to 5 lacs",
                    "Between 5 lacs to 10 lacs",
                    "Between 10 lacs to 30 lacs",
                    "More than 30 lacs",
                  ]
            },
        ]
    },
    {
        section_name: "Admission Details",
        section_visibilty: true,
        section_key: "admissionDetails",
        form_checklist: [
            {
                form_checklist_name: "Seat Type",
                form_checklist_key: "student_seat_type",
                form_checklist_visibility: true,
                form_checklist_placeholder: "Select Seat Type",
                form_checklist_lable: "Seat Type",
                form_checklist_typo: "SELECT",
                form_checklist_typo_option_pl: []
            },
            {
                form_checklist_name: "Physically Handicapped",
                form_checklist_key: "student_ph",
                form_checklist_visibility: true,
                form_checklist_placeholder: "Select Physically Handicapped",
                form_checklist_lable: "Physically Handicapped",
                form_checklist_typo: "SELECT",
                form_checklist_typo_option_pl: ["Yes", "No"]
            },
            {
                form_checklist_name: "Physically Handicapped Type",
                form_checklist_key: "student_ph_type",
                form_checklist_visibility: true,
                form_checklist_placeholder: "Enter Physically Handicapped Type",
                form_checklist_lable: "Physically Handicapped Type",
                form_checklist_typo: "TEXT",
            },
            {
                form_checklist_name: "Defence Personnel Word",
                form_checklist_key: "student_defence_personnel_word",
                form_checklist_visibility: true,
                form_checklist_placeholder: "Select Defence Personnel Word",
                form_checklist_lable: "Defence Personnel Word",
                form_checklist_typo: "SELECT",
                form_checklist_typo_option_pl: ["Yes", "No"]
            },
            {
                form_checklist_name: "Marital Status",
                form_checklist_key: "student_marital_status",
                form_checklist_visibility: true,
                form_checklist_placeholder: "Select Marital Status",
                form_checklist_lable: "Marital Status",
                form_checklist_typo: "SELECT",
                form_checklist_typo_option_pl: ["UnMarried", "Married"]
            },
        ]
    },
    {
        section_name: "Previous Attended / Institute Details",
        section_visibilty: true,
        section_key: "previousAttendedInstituteDetails",
        form_checklist: [
            {
                form_checklist_name: "Board / University",
                form_checklist_key: "student_board_university",
                form_checklist_visibility: true,
                form_checklist_placeholder: "Enter Board / University",
                form_checklist_lable: "Board / University",
                form_checklist_typo: "TEXT",
            },
            {
                form_checklist_name: "Previous Institute Name",
                form_checklist_key: "student_previous_institute_name",
                form_checklist_visibility: true,
                form_checklist_placeholder: "Enter Previous Institute Name",
                form_checklist_lable: "Previous Institute Name",
                form_checklist_typo: "TEXT",
            },
            {
                form_checklist_name: "University Courses",
                form_checklist_key: "student_university_courses",
                form_checklist_visibility: true,
                form_checklist_placeholder: "Enter University Courses",
                form_checklist_lable: "University Courses",
                form_checklist_typo: "TEXT",
            },
            {
                form_checklist_name: "Passing Year",
                form_checklist_key: "student_year",
                form_checklist_visibility: true,
                form_checklist_placeholder: "Select Passing Year",
                form_checklist_lable: "Passing Year",
                form_checklist_typo: "TEXT",
            },
            {
                form_checklist_name: "Class",
                form_checklist_key: "student_previous_class",
                form_checklist_visibility: true,
                form_checklist_placeholder: "Select Class",
                form_checklist_lable: "Class",
                form_checklist_typo: "TEXT",
            },
            {
                form_checklist_name: "Marks",
                form_checklist_key: "student_previous_marks",
                form_checklist_visibility: true,
                form_checklist_placeholder: "Enter Marks",
                form_checklist_lable: "Marks",
                form_checklist_typo: "TEXT",
            },
            {
                form_checklist_name: "Percentage",
                form_checklist_key: "student_previous_percentage",
                form_checklist_visibility: true,
                form_checklist_placeholder: "Enter Percentage",
                form_checklist_lable: "Percentage",
                form_checklist_typo: "TEXT",
            },
            {
                form_checklist_name: "Seat No.",
                form_checklist_key: "student_previous_section",
                form_checklist_visibility: true,
                form_checklist_placeholder: "Enter Seat No.",
                form_checklist_lable: "Seat No.",
                form_checklist_typo: "TEXT",
            },
            {
                form_checklist_name: "LC / TC Attachment",
                form_checklist_key: "student_previous_lctc",
                form_checklist_visibility: true,
                form_checklist_placeholder: "Upload LC / TC Attachment",
                form_checklist_lable: "Upload LC / TC Attachment",
                form_checklist_typo: "FILE",
            },
            {
                form_checklist_name: "Marksheet Attachment",
                form_checklist_key: "student_previous_marksheet_attachment",
                form_checklist_visibility: true,
                form_checklist_placeholder: "Upload LC / TC Attachment",
                form_checklist_lable: "Upload LC / TC Attachment",
                form_checklist_typo: "FILE",
            },
        ]
    },
    {
        section_name: "Undertakings",
        section_visibilty: true,
        section_key: "undertakings",
        section_view: "View Sample",
        section_pdf: "",
        form_checklist: [
            {
                form_checklist_name: "Undertakings",
                form_checklist_key: "student_undertakings",
                form_checklist_visibility: true,
                form_checklist_placeholder: "Enter Undertakings",
                form_checklist_lable: "",
                form_checklist_typo: "CHECKBOX",
                form_checklist_sample: "I Agree",
                form_checklist_typo_option_pl: ["I Agree"]
            },
        ]
    },
    {
        section_name: "Anti-Ragging Affidavit By The Student",
        section_visibilty: true,
        section_key: "antiragging_affidavit",
        section_view: "View Sample",
        section_pdf: "",
        form_checklist: [
            {
                form_checklist_name: "Anti-Ragging Affidavit By The Student",
                form_checklist_key: "student_undertakings",
                form_checklist_visibility: true,
                form_checklist_placeholder: "Enter Anti-Ragging Affidavit By The Student",
                form_checklist_lable: "",
                form_checklist_typo: "CHECKBOX",
                form_checklist_sample: "I Agree",
                form_checklist_typo_option_pl: ["I Agree"]
            },
        ]
    },
    {
        section_name: "Documents",
        section_visibilty: true,
        section_key: "documents",
        form_checklist: [ 
            {
                form_checklist_name: "Aadhar Card Front",
                form_checklist_key: "studentAadharFrontCard",
                form_checklist_visibility: true,
                form_checklist_placeholder: "Upload Aadhar Front Card",
                form_checklist_lable: "Upload Aadhar Front Card",
                form_checklist_typo: "FILE",
            },
            {
                form_checklist_name: "Aadhar Card Back",
                form_checklist_key: "studentAadharBackCard",
                form_checklist_visibility: true,
                form_checklist_placeholder: "Upload Aadhar Back Card",
                form_checklist_lable: "Upload Aadhar Back Card",
                form_checklist_typo: "FILE",
            },
            {
                form_checklist_name: "Student's Signature",
                form_checklist_key: "student_signature",
                form_checklist_visibility: true,
                form_checklist_placeholder: "Upload Student's Signature",
                form_checklist_lable: "Upload Student's Signature",
                form_checklist_typo: "FILE",
            },
            {
                form_checklist_name: "Student Parent's Signature",
                form_checklist_key: "student_parents_signature",
                form_checklist_visibility: true,
                form_checklist_placeholder: "Upload Student Parent's Signature",
                form_checklist_lable: "Upload Student Parent's Signature",
                form_checklist_typo: "FILE",
            },
            {
                form_checklist_name: "Student PAN Card",
                form_checklist_key: "student_pan_card",
                form_checklist_visibility: true,
                form_checklist_placeholder: "Upload Student PAN Card",
                form_checklist_lable: "Upload Student PAN Card",
                form_checklist_typo: "FILE",
            },
            {
                form_checklist_name: "Student Ration Card",
                form_checklist_key: "student_ration_card",
                form_checklist_visibility: true,
                form_checklist_placeholder: "Upload Student Ration Card",
                form_checklist_lable: "Upload Student Ration Card",
                form_checklist_typo: "FILE",
            },
            {
                form_checklist_name: "Income Certificate",
                form_checklist_key: "incomeCertificate",
                form_checklist_visibility: true,
                form_checklist_placeholder: "Upload Income Certificate",
                form_checklist_lable: "Upload Income Certificate",
                form_checklist_typo: "FILE",
            },
            {
                form_checklist_name: "Leaving / Transfer Certificate",
                form_checklist_key: "leavingTransferCertificate",
                form_checklist_visibility: true,
                form_checklist_placeholder: "Upload Leaving / Transfer Certificate",
                form_checklist_lable: "Upload Leaving / Transfer Certificate",
                form_checklist_typo: "FILE",
            },
            {
                form_checklist_name: "Non - Creamy Layer Certificate",
                form_checklist_key: "nonCreamyLayerCertificate",
                form_checklist_visibility: true,
                form_checklist_placeholder: "Upload Non - Creamy Layer Certificate",
                form_checklist_lable: "Upload Non - Creamy Layer Certificate",
                form_checklist_typo: "FILE",
            },
            {
                form_checklist_name: "Domicile Certificate",
                form_checklist_key: "domicileCertificate",
                form_checklist_visibility: true,
                form_checklist_placeholder: "Upload Domicile Certificate",
                form_checklist_lable: "Upload Domicile Certificate",
                form_checklist_typo: "FILE",
            },
            {
                form_checklist_name: "Nationality Certificate",
                form_checklist_key: "nationalityCertificate",
                form_checklist_visibility: true,
                form_checklist_placeholder: "Upload Nationality Certificate",
                form_checklist_lable: "Upload Nationality Certificate",
                form_checklist_typo: "FILE",
            },
            {
                form_checklist_name: "Last Year Certificate",
                form_checklist_key: "lastYearMarksheet",
                form_checklist_visibility: true,
                form_checklist_placeholder: "Upload Last Year Certificate",
                form_checklist_lable: "Upload Last Year Certificate",
                form_checklist_typo: "FILE",
            },
            {
                form_checklist_name: "Joining Transfer Letter",
                form_checklist_key: "joiningTransferLetter",
                form_checklist_visibility: true,
                form_checklist_placeholder: "Upload Joining Transfer Letter",
                form_checklist_lable: "Upload Joining Transfer Letter",
                form_checklist_typo: "FILE",
            },
            {
                form_checklist_name: "Identity Document",
                form_checklist_key: "identityDocument",
                form_checklist_visibility: true,
                form_checklist_placeholder: "Upload Identity Document",
                form_checklist_lable: "Upload Identity Document",
                form_checklist_typo: "FILE",
            },
            {
                form_checklist_name: "University Eligibilty Form",
                form_checklist_key: "university_eligibility_form",
                form_checklist_visibility: true,
                form_checklist_placeholder: "Upload University Eligibilty Form",
                form_checklist_lable: "Upload University Eligibilty Form",
                form_checklist_typo: "FILE",
            },
            {
                form_checklist_name: "Physically Handicapped Certificate",
                form_checklist_key: "ph_certificate",
                form_checklist_visibility: true,
                form_checklist_placeholder: "Upload Physically Handicapped Certificate",
                form_checklist_lable: "Upload Physically Handicapped Certificate",
                form_checklist_typo: "FILE",
            },
            {
                form_checklist_name: "GAP Certificate",
                form_checklist_key: "gap_certificate",
                form_checklist_visibility: true,
                form_checklist_placeholder: "Upload GAP Certificate",
                form_checklist_lable: "Upload GAP Certificate",
                form_checklist_typo: "FILE",
            },
        ]
    }
]