name: Build and Push Docker Image and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Create 'Secret' folder and JSON file
      - name: Create Secret folder and JSON file
        run: |
          mkdir Secret
          echo "${{ secrets.FIREBASE_JSON }}" > Secret/qviple-user-firebase-adminsdk-4qvna-8582f91ae3.json
          # Debugging: Verify JSON content
          cat Secret/qviple-user-firebase-adminsdk-4qvna-8582f91ae3.json

      # Step 4: Install dependencies and build the Node.js project
      - name: Install dependencies
        run: npm install

      # Step 5: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 6: Build the Docker image
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/qviple-prod:latest .

      # Step 7: Push Docker image to Docker Hub
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/qviple-prod:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build  

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Configure AWS CLI
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      # Step 3: Update ECS Task definition using the Docker image built in the previous job
      - name: Update ECS Task definition
        id: task-def
        uses: pooriaghaedi/amazon-ecs-deploy-task-definition@main
        env:
          ECS_TASK_DEFINITION: "qviple-api-taskdef"  
          REGION: "ap-south-1"  
          IMAGE_URI: "${{ secrets.DOCKER_USERNAME }}/qviple-prod:latest"  
          ECS_CLUSTER: "Prod-qviple"  
          ECS_SERVICE: "qviple-service-prod"
