name: Deploy to ECS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Configure AWS CLI
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      # Step 3: Update ECS Task definition using the existing Docker image
      - name: Update ECS Task definition
        id: task-def
        uses: pooriaghaedi/amazon-ecs-deploy-task-definition@main
        env:
          ECS_TASK_DEFINITION: "qviple-api-taskdef"  # Your task definition name
          REGION: "ap-south-1"  # AWS region
          IMAGE_URI: "${{ secrets.DOCKER_USERNAME }}/qviple-prod:latest"  # Docker image URI
          ECS_CLUSTER: "Prod-qviple"  # Your ECS cluster name
          ECS_SERVICE: "qviple-service-prod"  # Your ECS service name
